/* ZEVA Academy — Formula sheet */
(function () {
  var T = function (ja, en, id) { return { ja: ja, en: en, id: id }; };
  var f = function (module, name, expr, note) { return { name: name, expr: expr, note: note, module: module }; };

  ZA.addFormulas([
    {
      group: T('時間', 'Time', 'Waktu'),
      items: [
        f('ie-02',
          T('稼働時間', 'Available time', 'Waktu kerja tersedia'),
          T('稼働時間 = 就業時間 − 計画停止時間（休憩・朝礼など）', 'Available time = Shift time − Planned non-production time (breaks, meetings)', 'Waktu tersedia = Jam kerja − Waktu non-produksi terencana (istirahat, rapat)'),
          T('タクトタイム計算の分子になります。', 'The numerator of the takt-time formula.', 'Pembilang pada rumus takt time.')),
        f('ie-02',
          T('タクトタイム', 'Takt time', 'Takt time'),
          T('TT = 稼働時間 ÷ 必要生産数', 'TT = Available time ÷ Required quantity', 'TT = Waktu tersedia ÷ Jumlah yang dibutuhkan'),
          T('需要で決まる基準値。例：25,200秒 ÷ 420個 = 60秒', 'Set by demand. Example: 25,200 s ÷ 420 units = 60 s', 'Ditentukan oleh permintaan. Contoh: 25.200 detik ÷ 420 unit = 60 detik')),
        f('ie-02',
          T('生産能力', 'Capacity', 'Kapasitas'),
          T('生産能力 = 稼働時間 ÷ ネックCT', 'Capacity = Available time ÷ Neck CT', 'Kapasitas = Waktu tersedia ÷ CT leher botol'),
          T('CT ≦ TT なら需要を満たせます。', 'Demand can be met when CT ≤ TT.', 'Permintaan terpenuhi jika CT ≤ TT.')),
        f('ie-03',
          T('正味時間', 'Normal time', 'Waktu normal'),
          T('正味時間 = 観測時間 × レーティング', 'Normal time = Observed time × Rating', 'Waktu normal = Waktu observasi × Rating'),
          T('レーティングは標準ペース＝100%として評価します。', 'Rating is judged against normal pace = 100%.', 'Rating dinilai terhadap kecepatan normal = 100%.')),
        f('ie-03',
          T('標準時間', 'Standard time', 'Waktu standar'),
          T('標準時間 = 観測時間 × レーティング × (1 + 余裕率)', 'Standard time = Observed time × Rating × (1 + Allowance)', 'Waktu standar = Waktu observasi × Rating × (1 + Kelonggaran)'),
          T('例：50秒 × 1.10 × 1.12 ≒ 61.6秒', 'Example: 50 s × 1.10 × 1.12 ≈ 61.6 s', 'Contoh: 50 detik × 1,10 × 1,12 ≈ 61,6 detik'))
      ]
    },
    {
      group: T('ラインバランス', 'Line balance', 'Keseimbangan lini'),
      items: [
        f('ie-06',
          T('編成効率（IEの基本式）', 'Line balance efficiency (basic IE formula)', 'Efisiensi keseimbangan lini (rumus dasar IE)'),
          T('編成効率 = ΣCT ÷ (ネックCT × 工程数) × 100%', 'Line balance efficiency = ΣCT ÷ (Neck CT × Number of processes) × 100%', 'Efisiensi keseimbangan lini = ΣCT ÷ (CT leher botol × Jumlah proses) × 100%'),
          T('100%に近いほど工程間の負荷が均等です。IEの基本式では基準をネックCTに置きます。ZEVAはタクトタイムを基準にします（次の式）。', 'Closer to 100% means a more even load. The basic IE formula uses the neck CT as its reference; ZEVA uses the takt time (next entry).', 'Semakin mendekati 100%, semakin merata bebannya. Rumus dasar IE memakai CT leher botol sebagai acuan; ZEVA memakai takt time (entri berikutnya).')),
        f('z3-03',
          T('編成効率（タクト基準）', 'Line balance efficiency (takt-based)', 'Efisiensi keseimbangan lini (berbasis takt)'),
          T('編成効率 = Σ基準サイクルタイム ÷（基準時間 × 工程数）× 100%　　基準時間 = タクトタイムとネックタイムの大きいほう', 'Line balance efficiency = Σ standard CT ÷ (reference time × number of processes) × 100%   Reference time = the larger of takt time and neck time', 'Efisiensi keseimbangan lini = Σ CT standar ÷ (waktu acuan × jumlah proses) × 100%   Waktu acuan = yang lebih besar antara takt time dan waktu leher botol'),
          T('ZEVAの計算方法。ネックタイムがタクトタイムを超えたときだけ基準がネックタイムに変わります（仕様書v29 16.5）。', 'The ZEVA method. The reference switches to the neck time only when the neck exceeds takt (spec v29, 16.5).', 'Metode ZEVA. Acuan beralih ke waktu leher botol hanya bila leher botol melampaui takt (spesifikasi v29, 16.5).')),
        f('ie-06',
          T('編成ロス', 'Line balance loss', 'Kerugian keseimbangan lini'),
          T('編成ロス = 100% − 編成効率', 'Line balance loss = 100% − line balance efficiency', 'Kerugian keseimbangan lini = 100% − efisiensi keseimbangan lini'),
          T('ネック工程以外で発生する手待ちの割合です。', 'The share of waiting at non-neck processes.', 'Porsi waktu tunggu pada proses selain leher botol.')),
        f('ie-06',
          T('必要人員（理論工程数）', 'Required workers (theoretical)', 'Jumlah pekerja yang dibutuhkan (teoretis)'),
          T('必要人員 = ΣCT ÷ TT', 'Required workers = ΣCT ÷ TT', 'Pekerja yang dibutuhkan = ΣCT ÷ TT'),
          T('小数点以下は切り上げて検討し、端数分は改善で吸収を狙います。', 'Round up, and aim to absorb the fraction through improvement.', 'Bulatkan ke atas, dan targetkan menyerap pecahannya melalui perbaikan.'))
      ]
    },
    {
      group: T('設備総合効率（OEE）', 'OEE', 'OEE'),
      items: [
        f('ie-07',
          T('時間稼働率', 'Availability', 'Availability'),
          T('時間稼働率 = (負荷時間 − 停止時間) ÷ 負荷時間', 'Availability = (Loading time − Downtime) ÷ Loading time', 'Availability = (Loading time − Waktu henti) ÷ Loading time'),
          T('故障・段取り・調整などの停止ロスで低下します。', 'Reduced by stops such as breakdowns and setup.', 'Turun karena henti seperti kerusakan dan setup.')),
        f('ie-07',
          T('性能稼働率', 'Performance', 'Performance'),
          T('性能稼働率 = (理想CT × 生産数) ÷ 稼働時間', 'Performance = (Ideal CT × Total output) ÷ Operating time', 'Performance = (CT ideal × Total output) ÷ Waktu operasi'),
          T('チョコ停・速度低下で低下します。', 'Reduced by minor stops and reduced speed.', 'Turun karena henti kecil dan kecepatan turun.')),
        f('ie-07',
          T('良品率', 'Yield rate', 'Rasio produk baik'),
          T('良品率 = Good ÷ 総生産数（Trialを除く）', 'Yield rate = Good ÷ total production (excluding Trial)', 'Rasio produk baik = Good ÷ total produksi (tanpa Trial)'),
          T('不良・手直し・立上りロスで低下します。', 'Reduced by defects, repair and start-up losses.', 'Turun karena cacat, perbaikan, dan kerugian start-up.')),
        f('ie-07',
          T('OEE', 'OEE', 'OEE'),
          T('OEE = 時間稼働率 × 性能稼働率 × 良品率', 'OEE = Availability × Performance × Yield rate', 'OEE = Availability × Performance × Rasio produk baik'),
          T('ZEVAではGPC-M指標、目標 ≧ 85%。結果（Y）の指標です。', 'In ZEVA a GPC-M metric, target ≥ 85%. It is a result (Y) indicator.', 'Dalam ZEVA metrik GPC-M, target ≥ 85%. Merupakan indikator hasil (Y).'))
      ]
    },
    {
      group: T('統計', 'Statistics', 'Statistik'),
      items: [
        f('ie-08',
          T('平均', 'Mean', 'Rata-rata'),
          T('x̄ = Σx<sub>i</sub> ÷ n', 'x̄ = Σx<sub>i</sub> ÷ n', 'x̄ = Σx<sub>i</sub> ÷ n'),
          T('分布の中心。バラツキは分かりません。', 'Centre of the distribution; says nothing about spread.', 'Pusat distribusi; tidak menunjukkan sebaran.')),
        f('ie-08',
          T('範囲', 'Range', 'Rentang'),
          T('R = Max − Min', 'R = Max − Min', 'R = Max − Min'),
          T('簡便なバラツキの尺度。', 'A simple measure of spread.', 'Ukuran sebaran yang sederhana.')),
        f('ie-08',
          T('標準偏差（標本）', 'Standard deviation (sample)', 'Simpangan baku (sampel)'),
          T('s = √( Σ(x<sub>i</sub> − x̄)² ÷ (n − 1) )', 's = √( Σ(x<sub>i</sub> − x̄)² ÷ (n − 1) )', 's = √( Σ(x<sub>i</sub> − x̄)² ÷ (n − 1) )'),
          T('母集団全体のデータなら n で割ります（σ）。', 'Divide by n when the data are the whole population (σ).', 'Bagi dengan n bila data adalah seluruh populasi (σ).')),
        f('ie-08',
          T('変動係数', 'Coefficient of variation', 'Koefisien variasi'),
          T('CV = σ ÷ μ', 'CV = σ ÷ μ', 'CV = σ ÷ μ'),
          T('平均の異なるデータのバラツキを比較できます。', 'Compares variation between data with different means.', 'Membandingkan variasi antar data dengan rata-rata berbeda.')),
        f('ie-08',
          T('正規分布の範囲', 'Normal distribution coverage', 'Cakupan distribusi normal'),
          T('μ ± 1σ ≒ 68.3%　μ ± 2σ ≒ 95.4%　μ ± 3σ ≒ 99.7%', 'μ ± 1σ ≈ 68.3%   μ ± 2σ ≈ 95.4%   μ ± 3σ ≈ 99.7%', 'μ ± 1σ ≈ 68,3%   μ ± 2σ ≈ 95,4%   μ ± 3σ ≈ 99,7%'),
          T('データがこの範囲に入る割合の目安です。', 'Share of data expected within each range.', 'Porsi data yang diharapkan berada dalam tiap rentang.')),
        f('ie-05',
          T('ワークサンプリングの必要観測数', 'Work sampling: required observations', 'Work sampling: jumlah observasi yang dibutuhkan'),
          T('n = z² × p(1 − p) ÷ e²　（信頼度95%なら z ≒ 2）', 'n = z² × p(1 − p) ÷ e²   (95% confidence: z ≈ 2)', 'n = z² × p(1 − p) ÷ e²   (kepercayaan 95%: z ≈ 2)'),
          T('p：推定比率、e：許容誤差（絶対値）。例：p = 0.7、e = 0.05 → n ≒ 336', 'p: estimated ratio, e: allowed error (absolute). Example: p = 0.7, e = 0.05 → n ≈ 336', 'p: rasio perkiraan, e: galat yang diizinkan (absolut). Contoh: p = 0,7, e = 0,05 → n ≈ 336'))
      ]
    },
    {
      group: T('管理図と工程能力', 'Control charts & capability', 'Peta kendali & kapabilitas'),
      items: [
        f('ie-09',
          T('X̄管理図の管理限界', 'X̄ chart control limits', 'Batas kendali peta X̄'),
          T('UCL / LCL = X̿ ± A<sub>2</sub> × R̄　（n = 5 のとき A<sub>2</sub> = 0.577）', 'UCL / LCL = X̿ ± A<sub>2</sub> × R̄   (n = 5: A<sub>2</sub> = 0.577)', 'UCL / LCL = X̿ ± A<sub>2</sub> × R̄   (n = 5: A<sub>2</sub> = 0,577)'),
          T('群平均の変化を監視します。', 'Monitors shifts in subgroup averages.', 'Memantau pergeseran rata-rata subgrup.')),
        f('ie-09',
          T('R管理図の管理限界', 'R chart control limits', 'Batas kendali peta R'),
          T('UCL = D<sub>4</sub> × R̄、LCL = D<sub>3</sub> × R̄　（n = 5 のとき D<sub>4</sub> = 2.114、D<sub>3</sub> = 0）', 'UCL = D<sub>4</sub> × R̄, LCL = D<sub>3</sub> × R̄   (n = 5: D<sub>4</sub> = 2.114, D<sub>3</sub> = 0)', 'UCL = D<sub>4</sub> × R̄, LCL = D<sub>3</sub> × R̄   (n = 5: D<sub>4</sub> = 2,114, D<sub>3</sub> = 0)'),
          T('群内バラツキの変化を監視します。', 'Monitors changes in within-subgroup variation.', 'Memantau perubahan variasi dalam subgrup.')),
        f('ie-09',
          T('σの推定（管理図から）', 'Estimating σ from the chart', 'Estimasi σ dari peta kendali'),
          T('σ ≒ R̄ ÷ d<sub>2</sub>　（n = 5 のとき d<sub>2</sub> = 2.326）', 'σ ≈ R̄ ÷ d<sub>2</sub>   (n = 5: d<sub>2</sub> = 2.326)', 'σ ≈ R̄ ÷ d<sub>2</sub>   (n = 5: d<sub>2</sub> = 2,326)'),
          T('工程が安定状態にあるときのみ有効です。', 'Valid only when the process is in statistical control.', 'Hanya berlaku bila proses dalam kendali statistik.')),
        f('ie-09',
          T('Cp', 'Cp', 'Cp'),
          T('Cp = (USL − LSL) ÷ 6σ', 'Cp = (USL − LSL) ÷ 6σ', 'Cp = (USL − LSL) ÷ 6σ'),
          T('中心のズレは考慮しません。', 'Ignores off-centring.', 'Tidak memperhitungkan pergeseran pusat.')),
        f('ie-09',
          T('Cpk', 'Cpk', 'Cpk'),
          T('Cpk = min(USL − μ, μ − LSL) ÷ 3σ', 'Cpk = min(USL − μ, μ − LSL) ÷ 3σ', 'Cpk = min(USL − μ, μ − LSL) ÷ 3σ'),
          T('目安 ≧ 1.33（十分）、≧ 1.67（非常に良い）。安定状態の確認が前提（シューハートの原則）。', 'Guideline ≥ 1.33 (sufficient), ≥ 1.67 (very good). Confirm stability first (Shewhart\'s principle).', 'Patokan ≥ 1,33 (cukup), ≥ 1,67 (sangat baik). Pastikan stabilitas lebih dulu (prinsip Shewhart).'))
      ]
    },
    {
      group: T('理論値 / ZEVA 指標', 'Theoretical value / ZEVA metrics', 'Metrik Nilai Teoretis / ZEVA'),
      items: [
        f('z2-02',
          T('V.Score', 'V.Score', 'V.Score'),
          T('V.Score = σ ÷ μ（作業時間）', 'V.Score = σ ÷ μ (work time)', 'V.Score = σ ÷ μ (waktu kerja)'),
          T('GPC-H指標、目標は< 0.1。判定は 0.1未満 極めて安定／0.1〜0.3 安定／0.3〜0.5 やや不安定／0.5〜1.0 不安定／1.0以上 非常に不安定。', 'A GPC-H metric with a target of < 0.1. Bands: < 0.1 extremely stable / 0.1–0.3 stable / 0.3–0.5 slightly unstable / 0.5–1.0 unstable / ≥ 1.0 very unstable.', 'Metrik GPC-H dengan target < 0,1. Pita: < 0,1 sangat stabil / 0,1–0,3 stabil / 0,3–0,5 agak tidak stabil / 0,5–1,0 tidak stabil / ≥ 1,0 sangat tidak stabil.')),
        f('z2-02',
          T('CT達成率', 'CT achievement rate', 'Rasio pencapaian CT'),
          T('CT達成率 = 標準CT以内で完了したサイクル数 ÷ 全サイクル数 × 100%', 'CT achievement = Cycles within standard CT ÷ All cycles × 100%', 'Pencapaian CT = Siklus dalam CT standar ÷ Semua siklus × 100%'),
          T('GPC-H指標、目標 ≧ 95%。', 'GPC-H metric, target ≥ 95%.', 'Metrik GPC-H, target ≥ 95%.')),
        f('z2-02',
          T('GPCバンド適合率', 'GPC band conformance rate', 'Rasio kesesuaian GPC band'),
          T('適合率 = GPC_min 〜 GPC_max に入った測定数 ÷ 全測定数 × 100%', 'Conformance = Measurements within GPC_min–GPC_max ÷ All measurements × 100%', 'Kesesuaian = Pengukuran dalam GPC_min–GPC_max ÷ Semua pengukuran × 100%'),
          T('GPC-M指標、目標 ≧ 99%。', 'GPC-M metric, target ≥ 99%.', 'Metrik GPC-M, target ≥ 99%.')),
        f('z3-03',
          T('OLE（人的総合効率）', 'OLE (Overall Labor Effectiveness)', 'OLE (Overall Labor Effectiveness)'),
          T('OLE = 時間稼働率 × 性能稼働率 × 良品率', 'OLE = Availability × Performance × Yield rate', 'OLE = Availability × Performance × Rasio produk baik'),
          T('人の作業の総合効率。GPC-H指標、目標 ≧ 85%。低いときはV.ScoreとCT達成率で分解します。', 'The overall effectiveness of human work. A GPC-H metric, target ≥ 85%. When it is low, break it down with V.Score and the CT achievement rate.', 'Efektivitas keseluruhan kerja manusia. Metrik GPC-H, target ≥ 85%. Bila rendah, uraikan dengan V.Score dan rasio pencapaian CT.')),
        f('z3-03',
          T('不良率', 'Defect rate', 'Tingkat cacat'),
          T('不良率 =（Rework ＋ Repair ＋ Scrap）÷ 総生産数（Trialを除く）× 100%', 'Defect rate = (Rework + Repair + Scrap) ÷ Total production excluding Trial × 100%', 'Tingkat cacat = (Rework + Repair + Scrap) ÷ Total produksi tanpa Trial × 100%'),
          T('GPC-M指標。目標値は要求品質から製品・工程ごとに決めます。', 'GPC-M metric. The target is set per product and process from the required quality.', 'Metrik GPC-M. Target ditetapkan per produk dan proses dari kualitas yang diminta.')),
        f('z3-03',
          T('流出率', 'Outflow rate', 'Tingkat aliran keluar'),
          T('流出率 = その工程で発生し後工程以降で見つかった不良数 ÷ その工程の総生産数（Trialを除く）× 100%', 'Outflow rate = Defects made in the process and found in a later process ÷ Total production of that process excluding Trial × 100%', 'Tingkat aliran keluar = Cacat yang dibuat di proses itu dan ditemukan di proses selanjutnya ÷ Total produksi proses itu tanpa Trial × 100%'),
          T('自工程完結が成り立っているかを測ります。不良は発生工程と発見工程の両方を記録します。', 'Measures whether own-process completion holds. Record both the process of origin and the process of detection for each defect.', 'Mengukur apakah penyelesaian di proses sendiri terpenuhi. Catat proses asal dan proses penemuan untuk setiap cacat.')),
        f('z1-04',
          T('価値作業比率', 'Value-work ratio', 'Rasio pekerjaan bernilai'),
          T('価値作業比率 = 価値作業時間 ÷ 総作業時間 × 100%', 'Value-work ratio = Value-work time ÷ Total work time × 100%', 'Rasio pekerjaan bernilai = Waktu pekerjaan bernilai ÷ Total waktu kerja × 100%'),
          T('一般的な現状は10〜30%、目標は50〜60%以上。', 'Typically 10–30% today; target 50–60% or more.', 'Umumnya 10–30% saat ini; target 50–60% atau lebih.')),
        f('z1-04',
          T('現場理論値', 'Site theoretical value', 'Nilai teoretis lapangan'),
          T('現場理論値 = 価値作業 + 準価値作業（必要最小限）', 'Site theoretical value = Value work + Semi-value work (minimum)', 'Nilai teoretis lapangan = Pekerjaan bernilai + Pekerjaan semi-bernilai (minimum)'),
          T('現行の設備・工法で到達可能な理想状態。', 'The ideal achievable with current equipment and methods.', 'Kondisi ideal yang dapat dicapai dengan mesin dan metode saat ini.')),
        f('z1-04',
          T('技術理論値', 'Technical theoretical value', 'Nilai teoretis teknis'),
          T('技術理論値 = 価値作業のみ', 'Technical theoretical value = Value work only', 'Nilai teoretis teknis = Hanya pekerjaan bernilai'),
          T('新技術・新工法で準価値作業も排除した理想状態。', 'The ideal when new technology also removes semi-value work.', 'Kondisi ideal ketika teknologi baru juga menghilangkan pekerjaan semi-bernilai.')),
        f('z1-04',
          T('管理ロス', 'Management loss', 'Kerugian manajemen'),
          T('管理ロス = 現状 − 現場理論値（＝無価値作業）', 'Management loss = Current − Site theoretical value (= non-value work)', 'Kerugian manajemen = Saat ini − Nilai teoretis lapangan (= pekerjaan tanpa nilai)'),
          T('管理の改善で解消します。', 'Resolved by better management.', 'Diatasi dengan manajemen yang lebih baik.')),
        f('z1-04',
          T('技術ロス', 'Technical loss', 'Kerugian teknis'),
          T('技術ロス = 現場理論値 − 技術理論値（＝準価値作業）', 'Technical loss = Site theoretical value − Technical theoretical value (= semi-value work)', 'Kerugian teknis = Nilai teoretis lapangan − Nilai teoretis teknis (= pekerjaan semi-bernilai)'),
          T('工法改善・設備投資で解消します。', 'Resolved by method change or equipment investment.', 'Diatasi dengan perubahan metode atau investasi peralatan.')),
        f('z1-04',
          T('設計的アプローチ（絶対値思考）', 'Design approach (absolute-value thinking)', 'Pendekatan desain (berpikir nilai absolut)'),
          T('理論値 + 準価値 = あるべき姿　（対比：現状 − ムダ = 改善後）', 'Theoretical value + Semi-value = Target state   (vs. Current − Waste = Improved)', 'Nilai teoretis + Semi-bernilai = Kondisi seharusnya   (vs. Saat ini − Pemborosan = Hasil perbaikan)'),
          T('現状の延長ではなく、あるべき姿から逆算します。', 'Work backward from the ideal instead of extending the present.', 'Hitung mundur dari kondisi ideal, bukan melanjutkan kondisi saat ini.')),
        f('z2-03',
          T('シーケンス累積の法則（考え方）', 'Sequence accumulation (intuition)', 'Akumulasi urutan (intuisi)'),
          T('全動作の成功確率 = (1 − p)<sup>n</sup>　（p：1動作あたりのミス確率、n：動作数）', 'Probability all motions succeed = (1 − p)<sup>n</sup>   (p: error probability per motion, n: number of motions)', 'Peluang semua gerakan berhasil = (1 − p)<sup>n</sup>   (p: peluang kesalahan per gerakan, n: jumlah gerakan)'),
          T('例：p = 1%、n = 30 → 約74%。動作を減らすほど安定します。', 'Example: p = 1%, n = 30 → about 74%. Fewer motions = more stable.', 'Contoh: p = 1%, n = 30 → sekitar 74%. Semakin sedikit gerakan, semakin stabil.'))
      ]
    }
  ]);
})();
