/* ZEVA Academy — Glossary (ja / en / id) */
(function () {
  var T = function (ja, en, id) { return { ja: ja, en: en, id: id }; };
  var g = function (id, cat, module, term, def, abbr) {
    var o = { id: id, cat: cat, term: term, def: def, module: module };
    if (abbr) o.abbr = abbr;
    return o;
  };

  ZA.addGlossary([
    /* ---------- ie-01 ---------- */
    g('industrial-engineering', 'ie', 'ie-01',
      T('インダストリアル・エンジニアリング', 'Industrial Engineering', 'Industrial Engineering (Teknik Industri)'),
      T('人・設備・材料・情報を組み合わせた生産システムを、工学的な手法で設計・改善・運用する技術です。時間研究・動作研究・工程分析などを用いて、ムダ・ムリ・ムラを排除し生産性を高めます。',
        'An engineering discipline that designs, improves and operates production systems made of people, equipment, materials and information. It uses time study, motion study and process analysis to remove waste, overburden and unevenness.',
        'Disiplin rekayasa untuk merancang, memperbaiki, dan menjalankan sistem produksi yang terdiri dari manusia, mesin, material, dan informasi. Menggunakan studi waktu, studi gerakan, dan analisis proses untuk menghilangkan pemborosan, beban berlebih, dan ketidakrataan.'),
      'IE'),
    g('productivity', 'ie', 'ie-01',
      T('生産性', 'Productivity', 'Produktivitas'),
      T('投入（人・時間・設備・材料など）に対して得られる産出（生産量・付加価値）の比率です。生産性 = 産出 ÷ 投入。',
        'The ratio of output (quantity or added value) to input (labour, time, equipment, material). Productivity = Output ÷ Input.',
        'Rasio antara output (jumlah atau nilai tambah) terhadap input (tenaga kerja, waktu, mesin, material). Produktivitas = Output ÷ Input.')),
    g('qcds', 'ie', 'ie-01',
      T('QCDS', 'QCDS', 'QCDS'),
      T('Quality（品質）・Cost（コスト）・Delivery（納期）・Safety（安全）の頭文字で、ものづくりの基本的な評価軸です。Environment（環境）を加えてQCDSEとすることもあります。',
        'Quality, Cost, Delivery and Safety — the basic evaluation axes of manufacturing. Environment is sometimes added (QCDSE).',
        'Quality (kualitas), Cost (biaya), Delivery (pengiriman), Safety (keselamatan) — sumbu evaluasi dasar manufaktur. Kadang ditambah Environment (QCDSE).'),
      'QCDS'),
    g('4m', 'ie', 'ie-01',
      T('4M', '4M', '4M'),
      T('生産を構成する4つの基本要素、Man（人）・Machine（設備）・Material（材料）・Method（方法）です。品質や時間のバラツキの原因を整理する枠組みとして使われます。',
        'The four basic elements of production: Man, Machine, Material and Method. Used as a framework to sort the causes of variation in quality and time.',
        'Empat elemen dasar produksi: Man (manusia), Machine (mesin), Material, dan Method (metode). Digunakan sebagai kerangka untuk mengelompokkan penyebab variasi kualitas dan waktu.'),
      '4M'),
    g('value-added', 'ie', 'ie-01',
      T('付加価値', 'Value added', 'Nilai tambah'),
      T('お客様が対価を払う、製品の形・性質・機能を変化させる活動によって生まれる価値です。付加価値を生まない活動はムダとみなされます。',
        'Value created by activities that change the shape, properties or function of a product in a way the customer pays for. Activities that add no value are regarded as waste.',
        'Nilai yang tercipta dari aktivitas yang mengubah bentuk, sifat, atau fungsi produk yang dibayar pelanggan. Aktivitas yang tidak menambah nilai dianggap pemborosan.')),
    g('muda', 'ie', 'ie-01',
      T('ムダ', 'Muda (waste)', 'Muda (pemborosan)'),
      T('付加価値を生まず、コストだけを増やす活動や状態です。代表例として「7つのムダ」があります。',
        'Any activity or state that adds cost but no value. The "seven wastes" are typical examples.',
        'Setiap aktivitas atau kondisi yang menambah biaya tanpa menambah nilai. "Tujuh pemborosan" adalah contoh utamanya.')),
    g('muri', 'ie', 'ie-01',
      T('ムリ', 'Muri (overburden)', 'Muri (beban berlebih)'),
      T('人や設備に能力以上の負荷をかけている状態です。疲労・故障・品質不良・安全問題の原因になります。',
        'A state in which people or equipment are loaded beyond their capability. It causes fatigue, breakdowns, defects and safety problems.',
        'Kondisi ketika manusia atau mesin dibebani melebihi kemampuannya. Menyebabkan kelelahan, kerusakan, cacat, dan masalah keselamatan.')),
    g('mura', 'ie', 'ie-01',
      T('ムラ', 'Mura (unevenness)', 'Mura (ketidakrataan)'),
      T('作業時間・品質・負荷・生産量などが一定せずバラつく状態です。ムラはムダとムリを生み出す源であり、ZEVAが最重視する「バラツキ」に直結します。',
        'Unevenness in work time, quality, load or output. Mura breeds muda and muri, and corresponds directly to the "variation" that ZEVA focuses on.',
        'Ketidakrataan waktu kerja, kualitas, beban, atau output. Mura melahirkan muda dan muri, dan berhubungan langsung dengan "variasi" yang menjadi fokus ZEVA.')),
    g('seven-wastes', 'ie', 'ie-01',
      T('7つのムダ', 'Seven wastes', 'Tujuh pemborosan'),
      T('つくりすぎ・手待ち・運搬・加工そのもの・在庫・動作・不良をつくるムダの7種類です。現場のムダを見つけるためのチェックリストとして使います。',
        'Overproduction, waiting, transportation, over-processing, inventory, motion and defects. Used as a checklist for finding waste on the shop floor.',
        'Produksi berlebih, menunggu, transportasi, proses berlebih, persediaan, gerakan, dan cacat. Digunakan sebagai daftar periksa untuk menemukan pemborosan di lantai produksi.')),

    /* ---------- ie-02 ---------- */
    g('takt-time', 'ie', 'ie-02',
      T('タクトタイム', 'Takt time', 'Takt time'),
      T('お客様の需要に合わせて1個をつくるべき時間です。TT = 稼働時間 ÷ 必要生産数。市場の需要で決まり、生産側が勝手に変えられない基準値です。',
        'The time in which one unit should be produced to match customer demand. TT = Available time ÷ Required quantity. It is set by demand, not by production capability.',
        'Waktu yang seharusnya dipakai untuk membuat satu unit agar sesuai permintaan pelanggan. TT = Waktu kerja tersedia ÷ Jumlah yang dibutuhkan. Ditentukan oleh permintaan, bukan oleh kemampuan produksi.'),
      'TT'),
    g('cycle-time', 'ie', 'ie-02',
      T('サイクルタイム', 'Cycle time', 'Cycle time'),
      T('1つの工程（または1人の作業者）が1サイクルの作業を実際に完了するのにかかる時間です。現場の実力を表し、TTと比較して能力の過不足を判断します。',
        'The actual time a process (or operator) takes to complete one cycle of work. It shows real capability and is compared with TT to judge over- or under-capacity.',
        'Waktu aktual yang dibutuhkan satu proses (atau operator) untuk menyelesaikan satu siklus kerja. Menunjukkan kemampuan nyata dan dibandingkan dengan TT.'),
      'CT'),
    g('lead-time', 'ie', 'ie-02',
      T('リードタイム', 'Lead time', 'Lead time'),
      T('受注や材料投入から製品完成・出荷までにかかる経過時間の合計です。加工時間だけでなく、停滞・運搬・検査の時間も含みます。',
        'The total elapsed time from order or material input to product completion or shipment. It includes waiting, transport and inspection time, not only processing time.',
        'Total waktu yang berlalu dari pesanan atau masuknya material sampai produk selesai atau dikirim. Termasuk waktu tunggu, transportasi, dan inspeksi, bukan hanya waktu proses.'),
      'LT'),
    g('available-time', 'ie', 'ie-02',
      T('稼働時間（可動時間）', 'Available time', 'Waktu kerja tersedia'),
      T('生産に使える正味の時間で、就業時間から休憩・朝礼など計画的に生産しない時間を差し引いたものです。タクトタイム計算の分子になります。',
        'The net time available for production: shift time minus planned non-production time such as breaks and meetings. It is the numerator of the takt-time formula.',
        'Waktu bersih yang tersedia untuk produksi: jam kerja dikurangi waktu non-produksi terencana seperti istirahat dan rapat. Menjadi pembilang pada rumus takt time.')),
    g('capacity', 'ie', 'ie-02',
      T('生産能力', 'Capacity', 'Kapasitas'),
      T('一定時間内に生産できる最大の数量です。ラインの能力はネック工程のCTで決まり、能力 = 稼働時間 ÷ ネックCT で求めます。',
        'The maximum quantity that can be produced in a given time. Line capacity is limited by the neck process: Capacity = Available time ÷ Neck CT.',
        'Jumlah maksimum yang dapat diproduksi dalam waktu tertentu. Kapasitas lini dibatasi proses leher botol: Kapasitas = Waktu tersedia ÷ CT leher botol.')),

    /* ---------- ie-03 ---------- */
    g('time-study', 'ie', 'ie-03',
      T('時間研究', 'Time study', 'Studi waktu'),
      T('作業を要素に分解し、ストップウォッチや動画で繰り返し時間を測定・分析する手法です。標準時間の設定や、時間のバラツキの発見に使います。',
        'A method that breaks work into elements and repeatedly measures and analyses their time with a stopwatch or video. Used to set standard time and to reveal time variation.',
        'Metode yang memecah pekerjaan menjadi elemen lalu mengukur dan menganalisis waktunya berulang kali dengan stopwatch atau video. Digunakan untuk menetapkan waktu standar dan menemukan variasi waktu.')),
    g('element-work', 'ie', 'ie-03',
      T('要素作業', 'Work element', 'Elemen kerja'),
      T('作業を、始まりと終わりが明確に区切れる最小単位の動作のまとまりに分けたものです（例：部品を取る、セットする、締める）。時間測定と改善の単位になります。',
        'A unit of work with a clearly defined start and end point (e.g. pick part, set, tighten). It is the unit for time measurement and improvement.',
        'Unit pekerjaan dengan titik awal dan akhir yang jelas (mis. ambil part, pasang, kencangkan). Menjadi satuan pengukuran waktu dan perbaikan.')),
    g('standard-time', 'ie', 'ie-03',
      T('標準時間', 'Standard time', 'Waktu standar'),
      T('決められた方法・条件で、標準的な熟練度の作業者が標準的なペースで作業を行うのに必要な時間です。標準時間 = 観測時間 × レーティング ×（1＋余裕率）。',
        'The time required for a qualified operator working at a normal pace to do a job by the specified method. Standard time = Observed time × Rating × (1 + Allowance).',
        'Waktu yang dibutuhkan operator terlatih dengan kecepatan normal untuk mengerjakan tugas dengan metode yang ditentukan. Waktu standar = Waktu observasi × Rating × (1 + Kelonggaran).'),
      'ST'),
    g('rating', 'ie', 'ie-03',
      T('レーティング', 'Rating (performance rating)', 'Rating (penilaian kecepatan)'),
      T('観測した作業者のペースを標準ペースと比べて評価する係数です（標準＝100%）。速い作業者の観測時間は上方に、遅い作業者は下方に補正して正味時間を求めます。',
        'A factor that compares the observed operator\'s pace with the normal pace (normal = 100%). It adjusts observed time to obtain normal time.',
        'Faktor yang membandingkan kecepatan operator yang diamati dengan kecepatan normal (normal = 100%). Digunakan untuk menyesuaikan waktu observasi menjadi waktu normal.')),
    g('allowance', 'ie', 'ie-03',
      T('余裕率', 'Allowance', 'Kelonggaran (allowance)'),
      T('生理的欲求・疲労・避けられない遅れなど、正味の作業以外に必要な時間を正味時間に対する割合で表したものです。',
        'The extra time for personal needs, fatigue and unavoidable delays, expressed as a percentage of normal time.',
        'Waktu tambahan untuk kebutuhan pribadi, kelelahan, dan keterlambatan yang tak terhindarkan, dinyatakan sebagai persentase waktu normal.')),
    g('pts', 'ie', 'ie-03',
      T('PTS法（既定時間標準法）', 'Predetermined Time Standards', 'Predetermined Time Standards'),
      T('基本動作ごとに予め定められた時間値を組み合わせて作業時間を求める方法です。MTMやWFが代表例で、実測せずに設計段階で時間を見積もれます。',
        'A method that builds work time from pre-set time values for basic motions. MTM and WF are typical; time can be estimated at design stage without stopwatch measurement.',
        'Metode yang menyusun waktu kerja dari nilai waktu yang telah ditetapkan untuk gerakan dasar. MTM dan WF adalah contohnya; waktu dapat diperkirakan saat desain tanpa pengukuran.'),
      'PTS'),

    /* ---------- ie-04 ---------- */
    g('therblig', 'ie', 'ie-04',
      T('サーブリッグ（動素）', 'Therblig', 'Therblig'),
      T('ギルブレスが考案した、人の作業動作を「つかむ」「運ぶ」「探す」など約18種類の基本動作に分類したものです。付加価値のある動素とムダな動素を見分けて動作改善に使います。',
        'About 18 basic motion elements (grasp, transport, search, etc.) defined by Gilbreth. Used to separate value-adding motions from wasteful ones for motion improvement.',
        'Sekitar 18 elemen gerakan dasar (memegang, memindahkan, mencari, dll.) yang didefinisikan oleh Gilbreth. Digunakan untuk memisahkan gerakan bernilai tambah dari gerakan pemborosan.')),
    g('motion-economy', 'ie', 'ie-04',
      T('動作経済の原則', 'Principles of motion economy', 'Prinsip ekonomi gerakan'),
      T('疲れが少なく効率の良い動作を実現するための原則集で、「身体の使用」「作業場の配置」「工具・設備の設計」に関する原則からなります。基本は「なくす・減らす・同時に・楽にする」です。',
        'A set of principles for efficient, low-fatigue motion, covering use of the body, arrangement of the workplace and design of tools and equipment. Core idea: eliminate, reduce, do simultaneously, make easier.',
        'Kumpulan prinsip untuk gerakan efisien dan tidak melelahkan, meliputi penggunaan tubuh, tata letak tempat kerja, serta desain alat dan peralatan. Inti: hilangkan, kurangi, lakukan bersamaan, permudah.')),
    g('work-area', 'ie', 'ie-04',
      T('作業域', 'Work area', 'Area kerja'),
      T('作業者が座ったまま・立ったまま手の届く範囲です。肘を曲げて届く「通常作業域」と、腕を伸ばして届く「最大作業域」があり、よく使う部品や工具は通常作業域に置きます。',
        'The reach of an operator\'s hands. The normal work area (forearm reach) and maximum work area (full-arm reach); frequently used parts and tools belong in the normal area.',
        'Jangkauan tangan operator. Ada area kerja normal (jangkauan lengan bawah) dan area kerja maksimum (jangkauan lengan penuh); part dan alat yang sering dipakai ditempatkan di area normal.')),

    /* ---------- ie-05 ---------- */
    g('process-analysis', 'ie', 'ie-05',
      T('工程分析', 'Process analysis', 'Analisis proses'),
      T('製品や作業者が経る一連の工程を、加工・運搬・停滞・検査などに分類して記録・分析する手法です。流れの中のムダを見える化します。',
        'A method that records and analyses the sequence of steps a product or worker goes through, classified into operation, transport, delay, inspection, etc. It makes waste in the flow visible.',
        'Metode untuk mencatat dan menganalisis urutan langkah yang dilalui produk atau pekerja, diklasifikasikan menjadi operasi, transportasi, menunggu, inspeksi, dll. Membuat pemborosan dalam aliran terlihat.')),
    g('process-symbols', 'ie', 'ie-05',
      T('工程記号', 'Process chart symbols', 'Simbol peta proses'),
      T('工程分析で用いる記号で、加工（○）・運搬（⇨ または小さな○）・停滞（▽ / D）・検査（□）などがあります。付加価値を生むのは加工だけです。',
        'Symbols used in process analysis: operation (○), transport (⇨), delay/storage (▽ / D) and inspection (□). Only operation adds value.',
        'Simbol dalam analisis proses: operasi (○), transportasi (⇨), menunggu/penyimpanan (▽ / D), dan inspeksi (□). Hanya operasi yang menambah nilai.')),
    g('flow-diagram', 'ie', 'ie-05',
      T('流れ線図（フローダイアグラム）', 'Flow diagram', 'Diagram aliran'),
      T('工場のレイアウト図上に、人や物の移動経路を線で書き込んだ図です。運搬距離の長さや動線の交差・逆行を見える化します。',
        'A layout drawing on which the movement paths of people or materials are drawn as lines. It reveals long transport distances, crossings and backtracking.',
        'Gambar tata letak yang di atasnya digambarkan jalur pergerakan orang atau material. Menunjukkan jarak transport yang panjang, persilangan, dan aliran balik.')),
    g('man-machine-chart', 'ie', 'ie-05',
      T('マン・マシンチャート', 'Man-machine chart', 'Man-machine chart'),
      T('人と機械の作業・待ちの時間配分を時間軸上に並べて図示したものです。人の手待ちや機械の停止を見つけ、多台持ちや同時作業の検討に使います。',
        'A time-scaled chart showing working and idle time of a person and a machine side by side. Used to find operator waiting or machine idle time and to plan multi-machine handling.',
        'Diagram berskala waktu yang menampilkan waktu kerja dan menganggur manusia dan mesin berdampingan. Digunakan untuk menemukan waktu tunggu operator atau mesin dan merencanakan penanganan multi-mesin.')),
    g('work-sampling', 'ie', 'ie-05',
      T('ワークサンプリング', 'Work sampling', 'Work sampling'),
      T('ランダムな瞬間に作業者や設備の状態を多数回観測し、その出現比率から稼働率や作業構成比を統計的に推定する方法です。観測数を増やすほど誤差が小さくなります。',
        'A statistical method that observes the state of workers or machines at many random moments and estimates utilisation or activity ratios from the frequency. More observations mean smaller error.',
        'Metode statistik yang mengamati kondisi pekerja atau mesin pada banyak saat acak dan memperkirakan rasio utilisasi atau aktivitas dari frekuensinya. Semakin banyak observasi, semakin kecil galatnya.')),

    /* ---------- ie-06 ---------- */
    g('line-balance', 'ie', 'ie-06',
      T('ラインバランス', 'Line balancing', 'Keseimbangan lini'),
      T('ライン内の各工程の作業量（CT）をできるだけ均等かつTTに近づけるよう作業を配分することです。バランスが悪いと、ネック工程以外で手待ちが発生します。',
        'Distributing work so that each process\'s CT is as even as possible and close to TT. Poor balance causes waiting at all processes except the neck.',
        'Membagi pekerjaan agar CT setiap proses serata mungkin dan mendekati TT. Keseimbangan buruk menyebabkan waktu tunggu di semua proses kecuali proses leher botol.')),
    g('neck-process', 'ie', 'ie-06',
      T('ネック工程', 'Neck (bottleneck) process', 'Proses leher botol (bottleneck)'),
      T('ライン内で最もCTが長く、ライン全体の出来高を制約している工程です。ネック工程の改善がライン能力の向上に直結します。',
        'The process with the longest CT, which limits the output of the whole line. Improving it directly raises line capacity.',
        'Proses dengan CT terpanjang yang membatasi output seluruh lini. Memperbaikinya langsung meningkatkan kapasitas lini.')),
    g('line-balance-efficiency', 'ie', 'ie-06',
      T('編成効率', 'Line balance efficiency', 'Efisiensi keseimbangan lini'),
      T('ラインのバランスの良さを示す指標です。編成効率 = 各工程の基準サイクルタイムの合計 ÷（基準時間 × 工程数）× 100%。100%に近いほど工程間の負荷が均等です。IEの基本式は基準時間にネックCTを置きますが、ZEVAは**タクトタイム**を基準にし、[[neck-time]]がタクトタイムを超えるときだけそれを基準にします（仕様書v29 16.5）。編成ロス ＝ 100% − 編成効率。',
        'An index of how well a line is balanced. Line balance efficiency = Σ standard CT ÷ (reference time × number of processes) × 100%. Closer to 100% means more even load. The basic IE formula puts the neck CT in the reference time; ZEVA measures against the **takt time** and switches to the [[neck-time|neck time]] only when the neck exceeds takt (spec v29, 16.5). Line balance loss = 100% − line balance efficiency.',
        'Indeks seberapa seimbang suatu lini. Efisiensi keseimbangan lini = Σ CT standar ÷ (waktu acuan × jumlah proses) × 100%. Semakin mendekati 100%, semakin merata bebannya. Rumus dasar IE memakai CT leher botol sebagai waktu acuan; ZEVA mengukurnya terhadap **takt time** dan beralih ke [[neck-time|waktu leher botol]] hanya bila leher botol melampaui takt (spesifikasi v29, 16.5). Kerugian keseimbangan lini = 100% − efisiensi keseimbangan lini.')),
    g('neck-time', 'zeva', 'z3-03',
      T('ネックタイム', 'Neck (bottleneck) time', 'Waktu leher botol (bottleneck)'),
      T('もっとも遅い工程の基準サイクルタイム（各工程の基準サイクルタイムの最大値）です。ラインが実際に流せるペースを決めます。ラインバランスの基準時間は、タクトタイムとネックタイムの大きいほうを使います（仕様書v29 16.5）。',
        'The standard cycle time of the slowest process (the maximum of the per-process standard cycle times). It sets the pace the line can actually run. The reference time for line balance is whichever is larger, the takt time or the neck time (spec v29, 16.5).',
        'Waktu siklus standar proses paling lambat (nilai maksimum dari waktu siklus standar tiap proses). Ini menentukan laju yang benar-benar bisa dijalankan lini. Waktu acuan untuk keseimbangan lini adalah yang lebih besar antara takt time dan waktu leher botol (spesifikasi v29, 16.5).')),
    g('yamazumi', 'ie', 'ie-06',
      T('山積み表', 'Yamazumi chart', 'Diagram yamazumi'),
      T('工程ごと（作業者ごと）の作業時間を要素作業の積み上げ棒グラフで表し、TTの線と比較する図です。ネック工程と編成ロスが一目で分かり、作業の再配分（山崩し）に使います。',
        'A stacked bar chart of work elements per process or operator, compared with a TT line. It shows the neck and the line balance loss at a glance and is used to rebalance work.',
        'Diagram batang bertumpuk elemen kerja per proses atau operator yang dibandingkan dengan garis TT. Menunjukkan leher botol dan kerugian keseimbangan lini secara sekilas dan dipakai untuk menyeimbangkan ulang.')),

    /* ---------- ie-07 ---------- */
    g('oee', 'ie', 'ie-07',
      T('設備総合効率', 'Overall Equipment Effectiveness', 'Overall Equipment Effectiveness'),
      T('設備がどれだけ有効に使われているかを示す指標です。OEE = 時間稼働率 × 性能稼働率 × 良品率。ZEVAではGPC-Mの評価指標（目標≧85%）であり、結果（Y）の指標です。',
        'An index of how effectively equipment is used. OEE = Availability × Performance × Yield rate. In ZEVA it is a GPC-M metric (target ≥ 85%) and a result (Y) indicator.',
        'Indeks seberapa efektif mesin digunakan. OEE = Availability × Performance × Rasio produk baik. Dalam ZEVA merupakan metrik GPC-M (target ≥ 85%) dan indikator hasil (Y).'),
      'OEE'),
    g('availability', 'ie', 'ie-07',
      T('時間稼働率', 'Availability', 'Availability (rasio waktu operasi)'),
      T('負荷時間（稼働すべき時間）のうち、設備が実際に稼働した時間の割合です。故障・段取り・調整などの停止ロスで低下します。',
        'The share of loading time in which the equipment actually runs. Reduced by stop losses such as breakdowns, setup and adjustment.',
        'Porsi loading time ketika mesin benar-benar beroperasi. Turun karena kerugian berhenti seperti kerusakan, setup, dan penyetelan.')),
    g('performance-rate', 'ie', 'ie-07',
      T('性能稼働率', 'Performance', 'Performance (rasio kinerja)'),
      T('稼働している時間の中で、本来の速度（理想CT）でどれだけ生産できたかの割合です。性能稼働率 = 理想CT × 生産数 ÷ 稼働時間。チョコ停や速度低下で下がります。',
        'How much was produced at the ideal speed during running time. Performance = Ideal CT × Output ÷ Operating time. Reduced by minor stops and speed loss.',
        'Seberapa banyak yang diproduksi pada kecepatan ideal selama waktu operasi. Performance = CT ideal × Output ÷ Waktu operasi. Turun karena henti kecil dan penurunan kecepatan.')),
    g('quality-rate', 'ie', 'ie-07',
      T('良品率', 'Yield rate', 'Rasio produk baik'),
      T('総生産数（Trialを除く）に対する、追加の修理も再加工もなしに良品になったもの（Good）の割合です。良品率 = Good ÷ 総生産数（Trialを除く）。手直しや再加工で良品に戻した分は数えません。OEEの構成要素です。',
        'The share of pieces that came out good with no repair or rework (Good) against total production excluding Trial. Yield rate = Good ÷ total production (excluding Trial). Pieces recovered by repair or rework do not count. It is a component of OEE.',
        'Porsi unit yang langsung baik tanpa perbaikan atau pengerjaan ulang (Good) terhadap total produksi tanpa Trial. Rasio produk baik = Good ÷ total produksi (tanpa Trial). Unit yang dipulihkan lewat perbaikan atau pengerjaan ulang tidak dihitung. Merupakan komponen OEE.')),
    g('six-big-losses', 'ie', 'ie-07',
      T('6大ロス', 'Six big losses', 'Enam kerugian besar'),
      T('設備効率を下げる6つのロスで、故障・段取り調整（停止ロス）、チョコ停空転・速度低下（性能ロス）、不良手直し・立上りロス（不良ロス）です。',
        'Six losses that reduce equipment effectiveness: breakdowns and setup/adjustment (availability), minor stops and reduced speed (performance), defects/repair and start-up losses (quality).',
        'Enam kerugian yang menurunkan efektivitas mesin: kerusakan dan setup/penyetelan (availability), henti kecil dan kecepatan turun (performance), cacat/perbaikan dan kerugian start-up (quality).')),

    /* ---------- ie-08 ---------- */
    g('mean', 'stat', 'ie-08',
      T('平均値', 'Mean', 'Rata-rata (mean)'),
      T('データの合計をデータ数で割った値で、分布の中心を表します。記号は母集団でμ、標本でx̄。平均だけではバラツキは分かりません。',
        'The sum of the data divided by the count; it represents the centre of a distribution. Symbol μ (population) or x̄ (sample). The mean alone says nothing about variation.',
        'Jumlah data dibagi banyaknya data; mewakili pusat distribusi. Simbol μ (populasi) atau x̄ (sampel). Rata-rata saja tidak menunjukkan variasi.'),
      'μ / x̄'),
    g('median', 'stat', 'ie-08',
      T('中央値', 'Median', 'Median'),
      T('データを小さい順に並べたときに中央に位置する値です。外れ値の影響を受けにくいという特徴があります。',
        'The middle value when data are sorted. It is robust against outliers.',
        'Nilai tengah ketika data diurutkan. Tidak mudah dipengaruhi pencilan (outlier).')),
    g('range', 'stat', 'ie-08',
      T('範囲（レンジ）', 'Range', 'Rentang (range)'),
      T('データの最大値と最小値の差（R = Max − Min）です。計算が簡単で、X̄-R管理図のR（群内のバラツキ）に使われます。',
        'The difference between the maximum and minimum (R = Max − Min). Easy to calculate; used as R (within-subgroup variation) in the X̄-R chart.',
        'Selisih nilai maksimum dan minimum (R = Max − Min). Mudah dihitung; dipakai sebagai R (variasi dalam subgrup) pada peta X̄-R.'),
      'R'),
    g('variance', 'stat', 'ie-08',
      T('分散', 'Variance', 'Varians'),
      T('各データと平均との差（偏差）を2乗して平均した値で、バラツキの大きさを表します。標本から母分散を推定する場合は n−1 で割ります。',
        'The average of squared deviations from the mean; a measure of spread. When estimating population variance from a sample, divide by n−1.',
        'Rata-rata kuadrat simpangan dari rata-rata; ukuran sebaran. Saat mengestimasi varians populasi dari sampel, dibagi dengan n−1.'),
      'σ²'),
    g('standard-deviation', 'stat', 'ie-08',
      T('標準偏差', 'Standard deviation', 'Simpangan baku'),
      T('分散の平方根で、データが平均からどれくらい散らばっているかを元データと同じ単位で表します。記号はσ（標本ではs）。',
        'The square root of the variance; it expresses how far data spread from the mean, in the same unit as the data. Symbol σ (sample: s).',
        'Akar kuadrat varians; menyatakan seberapa jauh data menyebar dari rata-rata dalam satuan yang sama. Simbol σ (sampel: s).'),
      'σ'),
    g('coefficient-of-variation', 'stat', 'ie-08',
      T('変動係数', 'Coefficient of variation', 'Koefisien variasi'),
      T('標準偏差を平均で割った値（CV = σ ÷ μ）です。単位や平均の大きさが異なるデータ同士でも、相対的なバラツキを比較できます。ZEVAのV.Scoreはこの考え方です。',
        'The standard deviation divided by the mean (CV = σ ÷ μ). It lets you compare relative variation between data with different units or averages. ZEVA\'s V.Score uses this idea.',
        'Simpangan baku dibagi rata-rata (CV = σ ÷ μ). Memungkinkan membandingkan variasi relatif antar data dengan satuan atau rata-rata berbeda. V.Score ZEVA memakai konsep ini.'),
      'CV'),
    g('histogram', 'stat', 'ie-08',
      T('ヒストグラム', 'Histogram', 'Histogram'),
      T('データを区間に分けて各区間の度数を棒で表したグラフです。分布の中心・広がり・形（二山、偏りなど）を把握できます。QC7つ道具の一つです。',
        'A bar chart of frequencies of data grouped into intervals. It shows the centre, spread and shape (bimodal, skewed, etc.) of a distribution. One of the QC seven tools.',
        'Grafik batang frekuensi data yang dikelompokkan dalam interval. Menunjukkan pusat, sebaran, dan bentuk distribusi (dua puncak, miring, dll.). Salah satu dari 7 alat QC.')),
    g('normal-distribution', 'stat', 'ie-08',
      T('正規分布', 'Normal distribution', 'Distribusi normal'),
      T('平均を中心に左右対称な釣鐘型の分布です。平均±1σに約68.3%、±2σに約95.4%、±3σに約99.7%のデータが入ります。',
        'A symmetric bell-shaped distribution around the mean. About 68.3% of data fall within ±1σ, 95.4% within ±2σ and 99.7% within ±3σ.',
        'Distribusi simetris berbentuk lonceng di sekitar rata-rata. Sekitar 68,3% data berada dalam ±1σ, 95,4% dalam ±2σ, dan 99,7% dalam ±3σ.')),

    /* ---------- ie-09 ---------- */
    g('common-cause', 'qc', 'ie-09',
      T('偶然原因（共通原因）', 'Common cause', 'Penyebab umum (common cause)'),
      T('工程に常に存在する、多数の小さな要因が重なって生じる避けにくい変動の原因です。偶然原因だけの工程は予測可能で安定しています。',
        'The many small, ever-present causes that produce natural variation in a process. A process with only common causes is stable and predictable.',
        'Banyak penyebab kecil yang selalu ada dan menghasilkan variasi alami dalam proses. Proses yang hanya memiliki penyebab umum stabil dan dapat diprediksi.')),
    g('special-cause', 'qc', 'ie-09',
      T('異常原因（特殊原因）', 'Special cause', 'Penyebab khusus (special cause)'),
      T('工具の破損・材料ロット変更・手順の逸脱など、特定できる原因による普段と異なる変動です。管理図で管理限界外の点や異常な並びとして検出し、取り除きます。',
        'An identifiable cause of unusual variation such as a broken tool, a new material lot or a deviation from procedure. Detected on a control chart as out-of-limit points or abnormal patterns and removed.',
        'Penyebab variasi tidak biasa yang dapat diidentifikasi seperti alat rusak, lot material baru, atau penyimpangan prosedur. Dideteksi pada peta kendali sebagai titik di luar batas atau pola abnormal, lalu dihilangkan.')),
    g('control-chart', 'qc', 'ie-09',
      T('管理図', 'Control chart', 'Peta kendali (control chart)'),
      T('データを時系列にプロットし、中心線と上下の管理限界線で工程が安定状態にあるかを判定するグラフです。シューハートが考案しました。',
        'A time-series chart with a centre line and upper/lower control limits used to judge whether a process is in statistical control. Invented by Shewhart.',
        'Grafik deret waktu dengan garis tengah dan batas kendali atas/bawah untuk menilai apakah proses berada dalam kendali statistik. Diciptakan oleh Shewhart.')),
    g('xbar-r-chart', 'qc', 'ie-09',
      T('X̄-R管理図', 'X̄-R chart', 'Peta kendali X̄-R'),
      T('小さな群（例：n=5）ごとの平均（X̄）と範囲（R）を2枚の管理図で監視する、計量値の代表的な管理図です。X̄図で平均の変化、R図で群内バラツキの変化を捉えます。',
        'The typical variables control chart that monitors subgroup averages (X̄) and ranges (R) of small subgroups (e.g. n = 5). The X̄ chart detects shifts in the mean; the R chart detects changes in within-group variation.',
        'Peta kendali data variabel yang umum, memantau rata-rata (X̄) dan rentang (R) subgrup kecil (mis. n = 5). Peta X̄ mendeteksi pergeseran rata-rata; peta R mendeteksi perubahan variasi dalam grup.')),
    g('control-limit', 'qc', 'ie-09',
      T('管理限界', 'Control limit', 'Batas kendali'),
      T('工程自身のデータから統計的に計算される境界線（通常は中心線±3σ）です。工程の「声」を表し、規格限界とは別物です。',
        'Boundaries calculated statistically from the process\'s own data (usually centre line ± 3σ). They are the "voice of the process" and are different from specification limits.',
        'Batas yang dihitung secara statistik dari data proses itu sendiri (biasanya garis tengah ± 3σ). Merupakan "suara proses" dan berbeda dari batas spesifikasi.'),
      'UCL / LCL'),
    g('spec-limit', 'qc', 'ie-09',
      T('規格限界', 'Specification limit', 'Batas spesifikasi'),
      T('設計や顧客の要求から決まる、製品特性の許容範囲の上限（USL）と下限（LSL）です。「お客様の声」を表します。',
        'The upper (USL) and lower (LSL) tolerance of a product characteristic set by design or customer requirements. They are the "voice of the customer".',
        'Toleransi atas (USL) dan bawah (LSL) karakteristik produk yang ditetapkan oleh desain atau pelanggan. Merupakan "suara pelanggan".'),
      'USL / LSL'),
    g('cp', 'qc', 'ie-09',
      T('工程能力指数 Cp', 'Process capability index Cp', 'Indeks kapabilitas proses Cp'),
      T('規格幅と工程のバラツキ幅（6σ）の比です。Cp =（USL − LSL）÷ 6σ。分布の中心のズレは考慮しません。',
        'The ratio of the specification width to the process spread (6σ). Cp = (USL − LSL) ÷ 6σ. It ignores off-centring.',
        'Rasio lebar spesifikasi terhadap sebaran proses (6σ). Cp = (USL − LSL) ÷ 6σ. Tidak memperhitungkan pergeseran pusat.'),
      'Cp'),
    g('cpk', 'qc', 'ie-09',
      T('工程能力指数 Cpk', 'Process capability index Cpk', 'Indeks kapabilitas proses Cpk'),
      T('分布の中心のズレも考慮した工程能力指数です。Cpk = min（USL − μ, μ − LSL）÷ 3σ。一般に1.33以上で十分とされ、工程が安定状態にあることが前提です。IEの一般知識として扱い、ZEVAでは工程の評価指標には使いません（ZEVAは管理図・OEE・V.Score・不良率で見ます）。',
        'A capability index that accounts for off-centring. Cpk = min(USL − μ, μ − LSL) ÷ 3σ. ≥ 1.33 is generally sufficient; it presupposes a process in statistical control. It is taught here as general IE knowledge: ZEVA does not use it as a process metric (ZEVA uses control charts, OEE, V.Score and the defect rate).',
        'Indeks kapabilitas yang memperhitungkan pergeseran pusat. Cpk = min(USL − μ, μ − LSL) ÷ 3σ. ≥ 1,33 umumnya cukup; mensyaratkan proses dalam kendali statistik. Diajarkan sebagai pengetahuan umum IE: ZEVA tidak memakainya sebagai metrik proses (ZEVA memakai peta kendali, OEE, V.Score, dan tingkat cacat).'),
      'Cpk'),
    g('statistical-control', 'qc', 'ie-09',
      T('統計的管理状態（安定状態）', 'State of statistical control', 'Kondisi kendali statistik (stabil)'),
      T('特殊原因による変動が排除され、変動が偶然原因のみで構成されている状態です。この状態にない工程には定義可能な工程能力が存在しません（シューハートの原則）。',
        'A state in which variation from special causes has been removed and only common causes remain. A process not in this state has no definable capability (Shewhart\'s principle).',
        'Kondisi ketika variasi dari penyebab khusus telah dihilangkan dan hanya tersisa penyebab umum. Proses yang tidak dalam kondisi ini tidak memiliki kapabilitas yang dapat didefinisikan (prinsip Shewhart).')),

    /* ---------- ie-10 ---------- */
    g('5s', 'ie', 'ie-10',
      T('5S', '5S', '5S'),
      T('整理・整頓・清掃・清潔・しつけの5つの活動です。不要物をなくし、必要な物をすぐ使える状態に保つことで、再現性の高い職場の土台をつくります。',
        'Sort, Set in order, Shine, Standardize and Sustain. By removing unnecessary items and keeping needed items ready to use, it builds the foundation of a reproducible workplace.',
        'Seiri (ringkas), Seiton (rapi), Seiso (resik), Seiketsu (rawat), Shitsuke (rajin). Dengan menghilangkan barang tak perlu dan menjaga barang perlu siap pakai, membangun fondasi tempat kerja yang dapat direproduksi.'),
      '5S'),
    g('3tei', 'ie', 'ie-10',
      T('3定', '3 Fixes (3-tei)', '3 Tetap (3-tei)'),
      T('定位置（どこに）・定品（何を）・定量（いくつ）を決めて守ることです。探す・迷うといった無価値作業とバラツキを物理的になくします。',
        'Fixed position (where), fixed item (what) and fixed quantity (how many). It physically removes non-value work such as searching and the variation it causes.',
        'Posisi tetap (di mana), barang tetap (apa), dan jumlah tetap (berapa). Secara fisik menghilangkan pekerjaan tanpa nilai seperti mencari dan variasi yang ditimbulkannya.')),
    g('standard-work', 'ie', 'ie-10',
      T('標準作業', 'Standard work', 'Kerja standar'),
      T('現時点で最良の、安全かつ品質とムダのない作業のやり方を決めたものです。タクトタイム・作業順序・標準手持ちの3要素で構成され、改善の基準になります。',
        'The currently best, safe, quality-assured and waste-free way of doing the work. It consists of takt time, work sequence and standard in-process stock, and serves as the baseline for improvement.',
        'Cara kerja terbaik saat ini yang aman, menjamin kualitas, dan bebas pemborosan. Terdiri dari takt time, urutan kerja, dan stok dalam proses standar, serta menjadi dasar perbaikan.')),
    g('ecrs', 'ie', 'ie-10',
      T('ECRS（改善の4原則）', 'ECRS', 'ECRS'),
      T('Eliminate（排除）・Combine（結合）・Rearrange（交換）・Simplify（簡素化）の順に改善案を検討する原則です。最優先は「その作業は本当に必要か」を問うEです。',
        'Eliminate, Combine, Rearrange, Simplify — consider improvement ideas in this order. The top priority is E: "is this work really needed?"',
        'Eliminate (hilangkan), Combine (gabungkan), Rearrange (atur ulang), Simplify (sederhanakan) — pertimbangkan ide perbaikan dalam urutan ini. Prioritas utama adalah E: "apakah pekerjaan ini benar-benar perlu?"'),
      'ECRS'),
    g('pdca', 'ie', 'ie-10',
      T('PDCAサイクル', 'PDCA cycle', 'Siklus PDCA'),
      T('Plan（計画）→ Do（実行）→ Check（確認）→ Act（処置）を繰り返して継続的に改善する管理サイクルです。',
        'A management cycle for continuous improvement: Plan → Do → Check → Act, repeated.',
        'Siklus manajemen untuk perbaikan berkelanjutan: Plan → Do → Check → Act, diulang terus.'),
      'PDCA'),
    g('five-why', 'qc', 'ie-10',
      T('なぜなぜ分析', '5 Whys', 'Analisis 5 Why'),
      T('発生した問題に対して「なぜ」を繰り返し（目安5回）、表面的な現象から真因にたどり着く分析方法です。',
        'An analysis method that repeatedly asks "why?" (about five times) to move from the symptom to the root cause.',
        'Metode analisis yang menanyakan "mengapa?" berulang kali (sekitar lima kali) untuk bergerak dari gejala ke akar penyebab.')),
    g('fishbone', 'qc', 'ie-10',
      T('特性要因図', 'Fishbone (cause-and-effect) diagram', 'Diagram tulang ikan (sebab-akibat)'),
      T('結果（特性）とそれに影響する要因の関係を魚の骨の形で整理した図です。4Mなどの大骨で要因を洗い出します。QC7つ道具の一つです。',
        'A fish-shaped diagram organising the relationship between an effect and its possible causes, using main bones such as 4M. One of the QC seven tools.',
        'Diagram berbentuk tulang ikan yang menyusun hubungan antara akibat dan penyebab yang mungkin, dengan tulang utama seperti 4M. Salah satu dari 7 alat QC.')),
    g('pareto', 'qc', 'ie-10',
      T('パレート図', 'Pareto chart', 'Diagram Pareto'),
      T('項目別の件数や損失を大きい順に並べた棒グラフと累積比率の折れ線を組み合わせた図です。「重要な少数」を見つけて優先順位を決めます。',
        'A bar chart of categories sorted by size combined with a cumulative-percentage line. It finds the "vital few" to set priorities.',
        'Grafik batang kategori yang diurutkan berdasarkan besarnya, dikombinasikan dengan garis persentase kumulatif. Menemukan "sedikit yang vital" untuk menentukan prioritas.')),
    g('qc-7-tools', 'qc', 'ie-10',
      T('QC7つ道具', 'QC seven tools', '7 alat QC'),
      T('パレート図・特性要因図・チェックシート・ヒストグラム・散布図・管理図・グラフ（または層別）の7つで、データに基づく品質改善の基本ツールです。',
        'Pareto chart, fishbone diagram, check sheet, histogram, scatter diagram, control chart and graphs (or stratification): the basic tools for data-based quality improvement.',
        'Diagram Pareto, diagram tulang ikan, lembar periksa, histogram, diagram pencar, peta kendali, dan grafik (atau stratifikasi): alat dasar perbaikan kualitas berbasis data.')),
    g('poka-yoke', 'qc', 'ie-10',
      T('ポカヨケ', 'Poka-yoke', 'Poka-yoke'),
      T('人のうっかりミスが起きても不良にならない、または不良を次工程に流さないようにする仕組みや治具です。',
        'A mechanism or jig that prevents human error from creating defects or from passing defects to the next process.',
        'Mekanisme atau jig yang mencegah kesalahan manusia menimbulkan cacat atau meneruskan cacat ke proses berikutnya.')),

    /* ---------- z1-01 ---------- */
    g('zeva', 'zeva', 'z1-01',
      T('ZEVA（バラツキゼロ生産システム）', 'ZEVA (Zero Variation Production System)', 'ZEVA (Zero Variation Production System)'),
      T('理論値を目的基盤、GPC（良品保証工程条件）を手法基盤とし、「バラツキの制御」を核心とした次世代の生産方式です。改善ツールではなく、生産活動全体を設計・運用する「生産方式」です。',
        'A next-generation production system with the theoretical value as its purpose foundation and GPC as its method foundation, centred on controlling variation. It is a production system for designing and running all production activity, not an improvement tool.',
        'Sistem produksi generasi berikutnya dengan nilai teoretis sebagai fondasi tujuan dan GPC sebagai fondasi metode, berpusat pada pengendalian variasi. Ini adalah sistem produksi, bukan sekadar alat perbaikan.'),
      'ZEVA'),
    g('zero-definition', 'zeva', 'z1-01',
      T('「ゼロ」の定義', 'Definition of "Zero"', 'Definisi "Zero"'),
      T('ZEVAの「ゼロ」はバラツキの完全消滅ではなく、「バラツキが制御下にあり、良品が保証され、かつ理論値への収束を継続している状態」を指します。第一段階は全パラメータをGPCバンド内に収めること、第二段階は分布の中心を理論値に近づけることです。',
        '"Zero" in ZEVA does not mean variation has vanished; it means variation is under control, good quality is guaranteed and convergence to the theoretical value continues. Stage 1: all parameters within the GPC band; Stage 2: move the distribution centre toward the theoretical value.',
        '"Zero" dalam ZEVA bukan berarti variasi hilang sama sekali, tetapi variasi terkendali, kualitas baik terjamin, dan konvergensi ke nilai teoretis terus berlanjut. Tahap 1: semua parameter dalam GPC band; Tahap 2: menggeser pusat distribusi ke nilai teoretis.')),
    g('center-aiming', 'zeva', 'z1-01',
      T('センター・エイミング（中心狙い）', 'Center-Aiming', 'Center-Aiming'),
      T('GPCバンド内に収まった分布の中心を、狙い値（Target＝理論値）に近づけていく活動です。「ゼロ」の第二段階（指向目標）にあたります。',
        'Moving the centre of a distribution that is already within the GPC band toward the Target (theoretical value). It is Stage 2 (the aspiration) of "Zero".',
        'Menggeser pusat distribusi yang sudah berada di dalam GPC band menuju Target (nilai teoretis). Ini adalah Tahap 2 (aspirasi) dari "Zero".')),
    g('four-layers', 'zeva', 'z1-01',
      T('ZEVAの4層構造', 'ZEVA four-layer structure', 'Struktur empat lapis ZEVA'),
      T('Layer 1 理論値（目的基盤）、Layer 2 ハイブリッド・トリアージ（振り分け）、Layer 3 GPC制御理論（手法基盤）、Layer 4 PDCA-S＋7要因＋XY思考（実行基盤）からなる実装構造です。上位層が下位層の行動指針を決めます。',
        'The implementation structure: Layer 1 theoretical value (purpose), Layer 2 Hybrid Triage (routing), Layer 3 GPC control theory (method), Layer 4 PDCA-S + 7 factors + XY thinking (execution). Upper layers guide lower layers.',
        'Struktur implementasi: Layer 1 nilai teoretis (tujuan), Layer 2 Hybrid Triage (pemilahan), Layer 3 teori kendali GPC (metode), Layer 4 PDCA-S + 7 faktor + berpikir XY (eksekusi). Lapisan atas mengarahkan lapisan bawah.')),

    /* ---------- z1-02 ---------- */
    g('root-logic', 'zeva', 'z1-02',
      T('根底ロジック', 'Root logic', 'Logika fundamental'),
      T('改善はデータに基づくアクションでなければならず、そのためには信頼性の高いデータ（バラツキが少なく偏りの無いデータ）が必要である、という論理連鎖です。ゆえに制御されていないバラツキを極限まで無くすことが、データに基づく改善の大前提になります。',
        'The chain of logic that improvement must be data-based action, which requires reliable data (low variation, no bias). Therefore eliminating uncontrolled variation as far as possible is the prerequisite for data-based improvement.',
        'Rantai logika bahwa perbaikan harus berupa tindakan berbasis data, yang memerlukan data andal (variasi kecil, tanpa bias). Karena itu menghilangkan variasi tak terkendali sejauh mungkin adalah prasyarat perbaikan berbasis data.')),
    g('shewhart-principle', 'zeva', 'z1-02',
      T('シューハートの原則', 'Shewhart\'s principle', 'Prinsip Shewhart'),
      T('「安定状態（統計的管理状態）にない工程には、定義可能な工程能力が存在しない」という原則です。不安定な工程では今日のデータが明日を予測しないため、不良率やV.Scoreは計算できても意味を持ちません。ZEVA根底ロジックの理論的基盤です。',
        '"A process that is not in statistical control has no definable process capability." In an unstable process today\'s data do not predict tomorrow, so the defect rate or V.Score can be calculated but mean nothing. It is the theoretical basis of ZEVA\'s root logic.',
        '"Proses yang tidak berada dalam kendali statistik tidak memiliki kapabilitas proses yang dapat didefinisikan." Pada proses tidak stabil, data hari ini tidak memprediksi besok, sehingga tingkat cacat atau V.Score bisa dihitung tetapi tidak bermakna. Ini dasar teoretis logika fundamental ZEVA.')),
    g('data-reliability', 'zeva', 'z1-02',
      T('データ信頼性', 'Data reliability', 'Keandalan data'),
      T('データがバラツキ（精度）と偏り（正確さ）の両面で信頼でき、アクションの根拠として使える度合いです。前提として工程が統計的管理状態にあることを要します。',
        'The degree to which data can be trusted in both variation (precision) and bias (accuracy) and used as a basis for action. It requires the process to be in statistical control.',
        'Tingkat kepercayaan data dari sisi variasi (presisi) dan bias (akurasi) sehingga dapat dijadikan dasar tindakan. Mensyaratkan proses berada dalam kendali statistik.')),
    g('precision', 'stat', 'z1-02',
      T('精度（精密さ）', 'Precision', 'Presisi'),
      T('同じものを繰り返し測ったときの値のバラツキの小ささです。精度が高い＝バラツキが小さい。正確さとは別の概念です。',
        'How small the spread is when the same thing is measured repeatedly. High precision = small variation. It is a different concept from accuracy.',
        'Seberapa kecil sebaran ketika hal yang sama diukur berulang kali. Presisi tinggi = variasi kecil. Konsep ini berbeda dari akurasi.')),
    g('accuracy', 'stat', 'z1-02',
      T('正確さ（真度）', 'Accuracy (trueness)', 'Akurasi'),
      T('測定値の平均が真の値にどれだけ近いか、すなわち偏り（バイアス）の小ささです。校正によって確保します。',
        'How close the average of measurements is to the true value, i.e. how small the bias is. Ensured by calibration.',
        'Seberapa dekat rata-rata hasil ukur dengan nilai sebenarnya, yaitu seberapa kecil biasnya. Dijamin melalui kalibrasi.')),

    /* ---------- z1-03 ---------- */
    g('foundation-standardization', 'zeva', 'z1-03',
      T('土台：標準化', 'Foundation: standardization', 'Fondasi: standardisasi'),
      T('ZEVAの3原則が機能するための前提条件で、5S・3定、4M標準、標準作業、再現性の確保を含みます。「標準無きところに改善なし」— 再現性の保証なくして測定も改善も成り立ちません。好循環の起点でもあります。',
        'The precondition for ZEVA\'s three principles, including 5S/3-tei, 4M standards, standard work and ensured reproducibility. "No improvement without standards" — without reproducibility neither measurement nor improvement works. It is also the starting point of the virtuous cycle.',
        'Prasyarat agar tiga prinsip ZEVA berfungsi, meliputi 5S/3-tei, standar 4M, kerja standar, dan jaminan reprodusibilitas. "Tidak ada perbaikan tanpa standar" — tanpa reprodusibilitas, pengukuran dan perbaikan tidak berjalan. Juga titik awal siklus positif.')),
    g('initial-standard', 'zeva', 'z1-03',
      T('初期標準', 'Initial standard', 'Standar awal'),
      T('標準化で最初に決める標準です。最適解ではなく、同じ方法・同じ測り方で比較できる共通条件（測れる状態）をつくるためのものです。',
        'The first standard decided when standardizing. It is not the optimum; its purpose is to create common conditions (a measurable state) where the same method and the same way of measuring allow comparison.',
        'Standar pertama yang ditetapkan saat standardisasi. Bukan solusi optimal; tujuannya menciptakan kondisi bersama (kondisi yang dapat diukur) sehingga metode dan cara ukur yang sama memungkinkan perbandingan.')),
    g('outcome-standard', 'zeva', 'z1-03',
      T('成果標準', 'Outcome standard', 'Standar hasil'),
      T('改善によって良くなった状態を固定した標準です。次の改善のスタートラインになり、初期標準から始まった土台を更新していきます。',
        'A standard that locks in the state improved through improvement activities. It becomes the starting line for the next improvement and keeps updating the foundation that began with the initial standard.',
        'Standar yang mengunci kondisi yang sudah membaik melalui perbaikan. Menjadi garis start perbaikan berikutnya dan terus memperbarui fondasi yang dimulai dari standar awal.')),
    g('quick-standardization', 'zeva', 'z1-03',
      T('Quick標準化', 'Quick standardization', 'Standardisasi Quick'),
      T('「決める → 守る → 改める」を速く回す通常の標準化です。初期標準は当日〜3日以内に決めるのが目安で、決めるときも「5つの問い」と仕様の確認は必ず行います。',
        'The normal way of standardizing: running "decide → keep → revise" quickly. The initial standard is decided on the same day, or within 3 days at most as a guide, and the "five questions" and the specification check are always done.',
        'Cara standardisasi yang biasa: menjalankan "tetapkan → jaga → revisi" dengan cepat. Standar awal ditetapkan pada hari yang sama, paling lambat dalam 3 hari sebagai patokan, dan "lima pertanyaan" serta pengecekan spesifikasi selalu dilakukan.')),
    g('deep-standardization', 'zeva', 'z1-03',
      T('Deep標準化', 'Deep standardization', 'Standardisasi Deep'),
      T('安全・重要品質特性・仕様要求が絡む箇所など、適用基準に該当する箇所に限り、Step 0〜8の手順で仕様の根拠から標準をつくる標準化です。振り分けは班長が判断し、工程技術者が確認します。',
        'Standardization that builds the standard from the specification basis with Steps 0–8, only where the criteria apply (safety, critical quality characteristics, specification requirements, etc.). The team leader decides which mode applies (Quick or Deep), and the process engineer confirms it.',
        'Standardisasi yang menyusun standar dari dasar spesifikasi dengan Langkah 0–8, hanya pada bagian yang memenuhi kriteria (keselamatan, karakteristik mutu penting, persyaratan spesifikasi, dll.). Ketua tim menentukan mode (Quick atau Deep) dan insinyur proses mengonfirmasinya.')),
    g('three-principles', 'zeva', 'z1-03',
      T('ZEVAの3原則', 'ZEVA\'s three principles', 'Tiga prinsip ZEVA'),
      T('①バラツキ対策（何に着目するか）、②理論値ベース思考（どこを目指すか）、③PDCA+S（どう定着・進化させるか）の3つです。標準化という土台の上に立ち、「土台→原則→改善→土台更新」の循環を駆動します。',
        '① Variation countermeasures (what to focus on), ② theoretical-value thinking (where to aim), ③ PDCA+S (how to sustain and evolve). They stand on the foundation of standardization and drive the cycle "foundation → principles → improvement → updated foundation".',
        '① Penanggulangan variasi (apa yang difokuskan), ② berpikir berbasis nilai teoretis (ke mana menuju), ③ PDCA+S (bagaimana mempertahankan dan mengembangkan). Berdiri di atas fondasi standardisasi dan menggerakkan siklus "fondasi → prinsip → perbaikan → fondasi diperbarui".')),

    /* ---------- z1-04 ---------- */
    g('theoretical-value', 'zeva', 'z1-04',
      T('理論値', 'Theoretical value', 'Nilai teoretis'),
      T('「価値作業だけを最速で流し、それ以外はすべてロスとして削る」という思想に基づく改善活動です。物理的・技術的な理想状態（理論値）を定義し、そこから逆算して目標を設計します。ZEVAの目的基盤（Layer 1）です。',
        'An improvement philosophy: "flow only value work at the fastest speed and cut everything else as loss". It defines the physically and technically ideal state (theoretical value) and designs targets backward from it. It is ZEVA\'s purpose foundation (Layer 1).',
        'Filosofi perbaikan: "alirkan hanya pekerjaan bernilai secepat mungkin dan pangkas sisanya sebagai kerugian". Mendefinisikan kondisi ideal secara fisik dan teknis (nilai teoretis) dan merancang target mundur darinya. Fondasi tujuan ZEVA (Layer 1).'),
      'Theoretical value'),
    g('value-work', 'zeva', 'z1-04',
      T('価値作業', 'Value work', 'Pekerjaan bernilai'),
      T('物の形・質を、製品が持つべき機能のために変化させている「瞬間」の作業です。境界は製品設計（Design）が決め、設計が変わらない限り必ず必要です（例：ボルトが規定トルクに達する瞬間）。',
        'The "moment" of work that changes the shape or properties of a product for its required function. Its boundary is set by product design; it is always needed unless the design changes (e.g. the moment a bolt reaches the specified torque).',
        '"Momen" kerja yang mengubah bentuk atau sifat produk demi fungsi yang diperlukan. Batasnya ditentukan desain produk; selalu diperlukan kecuali desain berubah (mis. saat baut mencapai torsi yang ditentukan).')),
    g('semi-value-work', 'zeva', 'z1-04',
      T('準価値作業', 'Semi-value work', 'Pekerjaan semi-bernilai'),
      T('価値作業に伴う、現在の工法を前提とした場合に必要最小限の作業です。境界は工法・プロセス（Process）が決め、工法を変えれば削減・排除できます（例：部品を掴む、治具にセットする）。',
        'The minimum work accompanying value work under the current method. Its boundary is set by the process/method and can be reduced or removed by changing the method (e.g. grasping a part, setting it in a jig).',
        'Pekerjaan minimum yang menyertai pekerjaan bernilai dengan metode saat ini. Batasnya ditentukan proses/metode dan dapat dikurangi atau dihilangkan dengan mengubah metode (mis. memegang part, memasang pada jig).')),
    g('non-value-work', 'zeva', 'z1-04',
      T('無価値作業', 'Non-value work', 'Pekerjaan tanpa nilai'),
      T('付加価値を一切生まない純粋なロスです。境界は実行・管理（Execution/Management）が決め、適切な管理下では本来ゼロにできます（例：歩行、手待ち、探す、手直し）。',
        'Pure loss that adds no value. Its boundary is set by execution/management, and it can in principle be made zero under proper management (e.g. walking, waiting, searching, repair).',
        'Kerugian murni yang tidak menambah nilai. Batasnya ditentukan pelaksanaan/manajemen dan pada prinsipnya dapat dibuat nol dengan manajemen yang tepat (mis. berjalan, menunggu, mencari, perbaikan).')),
    g('value-work-ratio', 'zeva', 'z1-04',
      T('価値作業比率', 'Value-work ratio', 'Rasio pekerjaan bernilai'),
      T('価値作業時間 ÷ 総作業時間 × 100% で表す、理論値ベースの改善の核心指標です。一般的な現状は10〜30%程度で、50〜60%以上を目標とします。',
        'Value-work time ÷ total work time × 100%; the core indicator of theoretical-value improvement. Typically 10–30% today, with a target of 50–60% or more.',
        'Waktu pekerjaan bernilai ÷ total waktu kerja × 100%; indikator inti perbaikan nilai teoretis. Umumnya 10–30% saat ini, dengan target 50–60% atau lebih.')),
    g('site-theoretical-value', 'zeva', 'z1-04',
      T('現場理論値', 'Site theoretical value', 'Nilai teoretis lapangan'),
      T('現行の設備・工法で到達可能な理想状態で、現場理論値 = 価値作業 + 準価値作業（必要最小限）です。まず目指すべき改善の到達点です。',
        'The ideal state achievable with current equipment and methods: site theoretical value = value work + semi-value work (minimum). The first improvement goal.',
        'Kondisi ideal yang dapat dicapai dengan mesin dan metode saat ini: nilai teoretis lapangan = pekerjaan bernilai + pekerjaan semi-bernilai (minimum). Target perbaikan pertama.')),
    g('technical-theoretical-value', 'zeva', 'z1-04',
      T('技術理論値', 'Technical theoretical value', 'Nilai teoretis teknis'),
      T('新技術・新工法を取り入れ、準価値作業も排除した理想状態で、技術理論値 = 価値作業のみ です。将来の技術開発や設備投資の指針になります。',
        'The ideal state in which new technology or methods also remove semi-value work: technical theoretical value = value work only. A guide for future technology development and investment.',
        'Kondisi ideal ketika teknologi atau metode baru juga menghilangkan pekerjaan semi-bernilai: nilai teoretis teknis = hanya pekerjaan bernilai. Panduan pengembangan teknologi dan investasi ke depan.')),
    g('required-quality', 'zeva', 'z1-04',
      T('要求品質', 'Required quality', 'Kualitas yang diminta'),
      T('その製品に求められる品質です。高ければ高いほどよいものではなく、企画・開発・生産のすべてで検討と検証を行い、量産で成立すること（量産妥当性）を確かめたうえで設定します。',
        'The quality the product is required to have. Higher is not always better: it is set after the planning, development and production functions have examined and verified it, and after mass-production feasibility has been confirmed.',
        'Kualitas yang harus dimiliki produk. Lebih tinggi tidak selalu lebih baik: ditetapkan setelah bidang perencanaan, pengembangan, dan produksi memeriksa dan memverifikasinya, serta setelah kelayakan produksi massal dipastikan.')),
    g('over-quality', 'zeva', 'z1-04',
      T('過剰品質', 'Over-quality', 'Kualitas berlebihan'),
      T('要求品質を超えた品質です。品質とコストはトレードオフなので、超えた分はコストだけが増え、価値は増えません。',
        'Quality beyond the required quality. Since quality and cost trade off, the excess only adds cost and adds no value.',
        'Kualitas di luar kualitas yang diminta. Karena kualitas dan biaya saling tukar, kelebihannya hanya menambah biaya dan tidak menambah nilai.')),
    g('required-cost', 'zeva', 'z1-04',
      T('要求コスト', 'Required cost', 'Biaya yang diminta'),
      T('生産側に設定されるコストの枠です。この範囲内で要求品質を確保します。検査や手直しを足して品質を押さえ込むと、この枠を超えます。',
        'The cost frame set on the production side. The required quality must be secured within it. Holding quality down by adding inspection and repair breaks this frame.',
        'Kerangka biaya yang ditetapkan di sisi produksi. Kualitas yang diminta harus dicapai di dalamnya. Menahan kualitas dengan menambah inspeksi dan perbaikan akan melampaui kerangka ini.')),
    g('good-range', 'zeva', 'z1-04',
      T('良品範囲', 'Good-part range', 'Rentang produk baik'),
      T('その条件なら良品になる範囲です。射出成形なら速すぎても遅すぎても不良になり、その間だけが良品範囲です。物理実験で確かめて工程条件の範囲として定めたものがGPCバンドです。',
        'The range of conditions that yields good parts. In injection moulding, both too fast and too slow produce defects; only the range in between is the good-part range. Confirmed by physical trials and fixed as a range of process conditions, it becomes the GPC band.',
        'Rentang kondisi yang menghasilkan produk baik. Pada injection moulding, terlalu cepat maupun terlalu lambat menimbulkan cacat; hanya rentang di antaranya yang merupakan rentang produk baik. Setelah dipastikan lewat uji fisik dan ditetapkan sebagai rentang kondisi proses, itu menjadi GPC band.')),
    g('management-loss', 'zeva', 'z1-04',
      T('管理ロス', 'Management loss', 'Kerugian manajemen'),
      T('現状と現場理論値とのギャップで、無価値作業からなるロスです。内訳は動作・停止・速度・品質・流れの5つのロス（[[loss-structure]]）です。管理の改善（3定、配置最適化、ECRSなど）ですぐに解消に取り組めます。',
        'The gap between the current state and the site theoretical value, made of non-value work. It breaks down into five losses: motion, stop, speed, quality and flow ([[loss-structure]]). It can be tackled immediately by better management (3-tei, layout, ECRS).',
        'Selisih antara kondisi saat ini dan nilai teoretis lapangan, terdiri dari pekerjaan tanpa nilai. Rinciannya terdiri atas lima kerugian: gerakan, henti, kecepatan, kualitas, dan aliran ([[loss-structure]]). Dapat segera ditangani dengan manajemen yang lebih baik (3-tei, tata letak, ECRS).')),
    g('technical-loss', 'zeva', 'z1-04',
      T('技術ロス', 'Technical loss', 'Kerugian teknis'),
      T('現場理論値と技術理論値とのギャップで、準価値作業からなるロスです。工法改善や設備投資によって解消します。',
        'The gap between the site and technical theoretical values, made of semi-value work. It is resolved by method changes or equipment investment.',
        'Selisih antara nilai teoretis lapangan dan teknis, terdiri dari pekerjaan semi-bernilai. Diatasi dengan perubahan metode atau investasi peralatan.')),
    g('absolute-value-thinking', 'zeva', 'z1-04',
      T('絶対値思考', 'Absolute-value thinking', 'Berpikir nilai absolut'),
      T('現状からムダを引き算する分析的アプローチ（現状 − ムダ = 改善後）ではなく、理論値を定義し準価値を足し算してあるべき姿を設計する設計的アプローチ（理論値 + 準価値 = あるべき姿）です。',
        'Instead of the analytic approach of subtracting waste from the current state (current − waste = improved), define the theoretical value and add necessary semi-value work to design the ideal (theoretical value + semi-value = target state).',
        'Alih-alih pendekatan analitis yang mengurangi pemborosan dari kondisi saat ini (saat ini − pemborosan = hasil), definisikan nilai teoretis lalu tambahkan pekerjaan semi-bernilai untuk merancang kondisi ideal (nilai teoretis + semi-bernilai = kondisi seharusnya).')),

    /* ---------- z1-05 ---------- */
    g('seven-factors', 'zeva', 'z1-05',
      T('7つのバラツキ要因', 'Seven variation factors', 'Tujuh faktor variasi'),
      T('ZEVAが制御対象とする入力（X）の7要因で、Man（人）・Machine（設備）・Material（材料）・Method（方法）・Measurement（測定）・Management（管理）・Environment（環境）です。それぞれGPC-MまたはGPC-Hで制御します。',
        'The seven input (X) factors ZEVA controls: Man, Machine, Material, Method, Measurement, Management and Environment. Each is controlled by GPC-M or GPC-H.',
        'Tujuh faktor input (X) yang dikendalikan ZEVA: Man, Machine, Material, Method, Measurement, Management, dan Environment. Masing-masing dikendalikan oleh GPC-M atau GPC-H.')),
    g('xy-thinking', 'zeva', 'z1-05',
      T('XY思考', 'XY thinking', 'Berpikir XY'),
      T('OEE・時間・品質は結果（Y）であり原因（X）ではない、と区別する考え方です。結果を良くするには上流の原因（7つのバラツキ要因）を制御します。Yを直接操作する（検査を厳しくする、急がせる、残業する）のはNGです。',
        'The mindset that OEE, time and quality are results (Y), not causes (X). To improve results, control the upstream causes (seven variation factors). Manipulating Y directly (stricter inspection, rushing workers, overtime) is not allowed.',
        'Pola pikir bahwa OEE, waktu, dan kualitas adalah hasil (Y), bukan penyebab (X). Untuk memperbaiki hasil, kendalikan penyebab di hulu (tujuh faktor variasi). Memanipulasi Y secara langsung (inspeksi lebih ketat, mempercepat pekerja, lembur) tidak diperbolehkan.')),

    /* ---------- z2-01 ---------- */
    g('gpc', 'zeva', 'z2-01',
      T('GPC（良品保証工程条件）', 'GPC (Good Process Conditions)', 'GPC (Good Process Conditions)'),
      T('物理実験により検証された「良品生成を保証する工程条件の範囲」を定義し、その範囲内での生産を保証する、ZEVAの手法基盤となる制御理論です。',
        'ZEVA\'s method-foundation control theory: define the range of process conditions verified by physical experiments to guarantee good products, and guarantee production within that range.',
        'Teori kendali yang menjadi fondasi metode ZEVA: mendefinisikan rentang kondisi proses yang diverifikasi dengan eksperimen fisik untuk menjamin produk baik, dan menjamin produksi dalam rentang tersebut.'),
      'GPC'),
    g('gpc-band', 'zeva', 'z2-01',
      T('GPCバンド', 'GPC band', 'GPC band'),
      T('良品が保証される工程条件の範囲で、GPC_min（下限）〜GPC_max（上限）と狙い値Target（理論値）で定義します。統計的な管理限界ではなく、物理実験で確認した良品保証範囲です。',
        'The range of process conditions that guarantees good products, defined by GPC_min, GPC_max and the Target (theoretical value). It is not a statistical control limit but a range confirmed by physical experiments.',
        'Rentang kondisi proses yang menjamin produk baik, didefinisikan oleh GPC_min, GPC_max, dan Target (nilai teoretis). Bukan batas kendali statistik, tetapi rentang yang dikonfirmasi dengan eksperimen fisik.')),

    /* ---------- z2-02 ---------- */
    g('gpc-m', 'zeva', 'z2-02',
      T('GPC-M（設備制御）', 'GPC-M (Machine)', 'GPC-M (Mesin)'),
      T('設備パラメータの範囲制御に特化した手法です。物理実験でGPCバンドを決め、記録で連続監視し、GPCバンド適合率・OEE・不良率・X̄-R管理図で評価します。',
        'The method specialised in range control of equipment parameters. Set the GPC band by physical experiment, monitor continuously by recording, and evaluate by band conformance rate, OEE, defect rate and X̄-R chart.',
        'Metode khusus untuk kendali rentang parameter mesin. Tetapkan GPC band dengan eksperimen fisik, pantau terus dengan pencatatan, dan evaluasi dengan rasio kesesuaian band, OEE, tingkat cacat, dan peta X̄-R.'),
      'GPC-M'),
    g('gpc-h', 'zeva', 'z2-02',
      T('GPC-H（人制御）', 'GPC-H (Human)', 'GPC-H (Manusia)'),
      T('人の作業バラツキの排除に特化した手法です。ECRSと動作安定の原理で作業を設計し、4M標準化で標準作業を定義し、CT計測によるV.ScoreとCT達成率で評価します。',
        'The method specialised in eliminating variation in human work. Design work with ECRS and the principles of motion stability, define standard work with 4M standards, and evaluate by V.Score and CT achievement rate from CT measurement.',
        'Metode khusus untuk menghilangkan variasi kerja manusia. Rancang kerja dengan ECRS dan prinsip stabilitas gerakan, definisikan kerja standar dengan standar 4M, dan evaluasi dengan V.Score dan rasio pencapaian CT.'),
      'GPC-H'),
    g('ole', 'zeva', 'z3-03',
      T('人的総合効率', 'Overall Labor Effectiveness', 'Overall Labor Effectiveness'),
      T('OLE = 時間稼働率 × 性能稼働率 × 良品率で表す、人の作業の総合的な生産効率です。設備を[[oee|OEE]]で見るのと同じ考え方で、GPC-Hの評価指標です。目標は85%以上。低いときは[[v-score]]と[[ct-achievement-rate]]でどの要素が落ちているかを分解します。',
        'The overall effectiveness of human work: OLE = Availability × Performance × Yield rate. It is the [[oee|OEE]] idea applied to people and is a GPC-H metric, with a target of ≥ 85%. When it is low, break it down with [[v-score]] and [[ct-achievement-rate]].',
        'Efektivitas keseluruhan kerja manusia: OLE = Availability × Performance × Rasio produk baik. Ini adalah gagasan [[oee|OEE]] yang diterapkan pada manusia dan merupakan metrik GPC-H dengan target ≥ 85%. Bila rendah, uraikan dengan [[v-score]] dan [[ct-achievement-rate]].'),
      'OLE'),
    g('v-score', 'zeva', 'z2-02',
      T('V.Score（バラツキスコア）', 'V.Score (Variation Score)', 'V.Score (Skor Variasi)'),
      T('作業時間の変動係数 V.Score = σ ÷ μ で、GPC-Hの核心指標です。目標は0.1未満。0.1〜0.3は安定、0.3〜0.5はやや不安定、0.5〜1.0は不安定、1.0以上は非常に不安定と判断します。解釈には工程の安定が前提です。',
        'The coefficient of variation of work time, V.Score = σ ÷ μ; the core GPC-H metric. Target < 0.1. 0.1–0.3 stable, 0.3–0.5 slightly unstable, 0.5–1.0 unstable, ≥ 1.0 very unstable. Interpretation presupposes a stable process.',
        'Koefisien variasi waktu kerja, V.Score = σ ÷ μ; metrik inti GPC-H. Target < 0,1. 0,1–0,3 stabil, 0,3–0,5 agak tidak stabil, 0,5–1,0 tidak stabil, ≥ 1,0 sangat tidak stabil. Interpretasi mensyaratkan proses yang stabil.'),
      'V.Score'),
    g('ct-achievement-rate', 'zeva', 'z2-02',
      T('CT達成率', 'CT achievement rate', 'Rasio pencapaian CT'),
      T('標準CT以内で完了したサイクルの割合です。GPC-Hの評価指標で、目標は95%以上です。',
        'The share of cycles completed within the standard CT. A GPC-H metric with a target of ≥ 95%.',
        'Porsi siklus yang selesai dalam CT standar. Metrik GPC-H dengan target ≥ 95%.')),
    g('band-conformance-rate', 'zeva', 'z2-02',
      T('GPCバンド適合率', 'GPC band conformance rate', 'Rasio kesesuaian GPC band'),
      T('測定値のうちGPCバンド内に収まった割合です。GPC-Mの評価指標で、目標は99%以上です。',
        'The share of measured values within the GPC band. A GPC-M metric with a target of ≥ 99%.',
        'Porsi nilai terukur yang berada dalam GPC band. Metrik GPC-M dengan target ≥ 99%.')),
    g('quality-category', 'zeva', 'z3-03',
      T('品質区分', 'Quality categories', 'Kategori kualitas'),
      T('品質ロスを数えるための記録単位です。Good（良品）／Rework（再加工）／Repair（手直し）／Scrap（廃棄）／Trial（試作・条件確認品）の5区分で記録します。区分は個数で数え、ロスは時間で数えます。',
        'The recording units for counting quality loss: Good, Rework, Repair, Scrap and Trial (pieces made to confirm conditions). Categories are counted in pieces; losses are counted in time.',
        'Satuan pencatatan untuk menghitung kerugian kualitas: Good, Rework, Repair, Scrap, dan Trial (barang uji coba untuk memastikan kondisi). Kategori dihitung dalam jumlah unit; kerugian dihitung dalam waktu.')),
    g('defect-rate', 'zeva', 'z3-03',
      T('不良率', 'Defect rate', 'Tingkat cacat'),
      T('（Rework ＋ Repair ＋ Scrap）÷ 総生産数（Trialを除く）です。品質ロスの大きさを表すGPC-Mの評価指標で、目標値は要求品質から製品・工程ごとに決めます。',
        '(Rework + Repair + Scrap) ÷ total production (excluding Trial). A GPC-M metric for the size of quality loss; the target is set per product and process from the required quality.',
        '(Rework + Repair + Scrap) ÷ total produksi (tanpa Trial). Metrik GPC-M untuk besarnya kerugian kualitas; targetnya ditetapkan per produk dan proses dari kualitas yang diminta.')),
    g('own-process-completion', 'zeva', 'z2-01',
      T('自工程完結', 'Own-process completion', 'Penyelesaian di proses sendiri'),
      T('条件（X）がGPCバンドの中にあり標準作業が守られているために、検査を足さなくても良品だけを次工程へ渡せる状態です。不良を受け取らない・造らない・流さない。原則や手法ではなく、GPC-M / GPC-Hが成り立った工程の状態と責任の持ち方を指します。',
        'The state in which only good products can be handed to the next process without added inspection, because the conditions (X) are inside the GPC band and standard work is followed. Do not accept, make or pass on defects. It is not a principle or a method but the state of a process where GPC-M / GPC-H holds, and the way responsibility is carried.',
        'Keadaan di mana hanya produk baik yang dapat diserahkan ke proses berikutnya tanpa inspeksi tambahan, karena kondisi (X) berada di dalam GPC band dan kerja standar dipatuhi. Tidak menerima, tidak membuat, tidak meneruskan cacat. Ini bukan prinsip atau metode, melainkan keadaan proses ketika GPC-M / GPC-H terpenuhi dan cara memikul tanggung jawab.')),
    g('judgment-criteria', 'zeva', 'z2-06',
      T('判断基準', 'Judgment criteria', 'Kriteria penilaian'),
      T('作業者がその場で良し悪しを判断するための基準です（限度見本・ゲージ・数値）。作業の急所ごとに標準作業に書き、要求品質から決めます。',
        'The criteria an operator uses to judge good or bad on the spot (limit samples, gauges, numbers). They are written into standard work at each key point and set from the required quality.',
        'Kriteria yang dipakai operator untuk menilai baik atau buruk di tempat (sampel batas, gauge, angka). Ditulis ke dalam kerja standar di setiap titik kunci dan ditentukan dari kualitas yang diminta.')),
    g('outflow-rate', 'zeva', 'z3-03',
      T('流出率', 'Outflow rate', 'Tingkat aliran keluar'),
      T('流出は、発見工程が発生工程より後ろにある不良です。流出率 ＝ その工程で発生し後工程以降で見つかった不良数 ÷ その工程の総生産数（Trialを除く）。自工程完結が成り立っているかを測ります。',
        'Outflow is a defect found in a process later than the one where it was made. Outflow rate = defects made in the process and found in a later process ÷ total production of that process (excluding Trial). It measures whether own-process completion holds.',
        'Aliran keluar adalah cacat yang ditemukan di proses setelah proses tempat cacat itu dibuat. Tingkat aliran keluar = cacat yang dibuat di proses itu dan ditemukan di proses selanjutnya ÷ total produksi proses itu (tanpa Trial). Mengukur apakah penyelesaian di proses sendiri terpenuhi.')),

    /* ---------- z2-03 ---------- */
    g('motion-stability', 'zeva', 'z2-03',
      T('動作安定の原理', 'Principles of motion stability', 'Prinsip stabilitas gerakan'),
      T('「すべての動作はバラツキの発生源である」という前提に立ち、GPC-Hで作業バラツキを構造的に排除するための3法則（距離・変位、シーケンス累積、拘束とガイド）です。',
        'Three laws (distance/displacement, sequence accumulation, constraint and guide) for structurally eliminating work variation in GPC-H, based on the premise that every motion is a source of variation.',
        'Tiga hukum (jarak/perpindahan, akumulasi urutan, pembatasan dan pemandu) untuk menghilangkan variasi kerja secara struktural dalam GPC-H, berdasarkan premis bahwa setiap gerakan adalah sumber variasi.')),
    g('distance-law', 'zeva', 'z2-03',
      T('距離・変位の法則', 'Law of distance and displacement', 'Hukum jarak dan perpindahan'),
      T('動作安定の第1法則。動作距離の短縮は、バラツキの許容範囲を物理的に縮小します。距離が短いほどズレる余地がありません。',
        'First law of motion stability: shortening motion distance physically shrinks the room for variation. The shorter the distance, the less room to deviate.',
        'Hukum pertama stabilitas gerakan: memperpendek jarak gerakan secara fisik mempersempit ruang variasi. Semakin pendek jaraknya, semakin kecil ruang untuk menyimpang.')),
    g('sequence-law', 'zeva', 'z2-03',
      T('シーケンス累積の法則', 'Law of sequence accumulation', 'Hukum akumulasi urutan'),
      T('動作安定の第2法則。動作数の削減は、バラツキ発生の機会そのものを消滅させます。動作を減らすことは「サイコロを振る回数」を減らすことです。',
        'Second law of motion stability: reducing the number of motions removes opportunities for variation. Fewer motions means "rolling the dice" fewer times.',
        'Hukum kedua stabilitas gerakan: mengurangi jumlah gerakan menghilangkan peluang terjadinya variasi. Lebih sedikit gerakan berarti lebih sedikit "melempar dadu".')),
    g('constraint-law', 'zeva', 'z2-03',
      T('拘束とガイドの法則', 'Law of constraint and guide', 'Hukum pembatasan dan pemandu'),
      T('動作安定の第3法則。自由度の制限は、バラツキの発生を構造的に封じます。ガイドやストッパーで拘束された動作は、バラツキがゼロに近づきます。',
        'Third law of motion stability: limiting degrees of freedom structurally blocks variation. Motions constrained by guides or stoppers approach zero variation.',
        'Hukum ketiga stabilitas gerakan: membatasi derajat kebebasan secara struktural mencegah variasi. Gerakan yang dibatasi pemandu atau stopper mendekati variasi nol.')),

    /* ---------- z2-04 ---------- */
    g('hybrid-triage', 'zeva', 'z2-04',
      T('ハイブリッド・トリアージ', 'Hybrid triage', 'Hybrid triage'),
      T('すべての改善課題を入口（Phase 0）で評価し、原因の見当・変数の数・リスク・データの4基準によってQuick GPCモードかDeep GPCモードに振り分ける仕組みです。ZEVAのLayer 2です。',
        'The mechanism that evaluates every improvement issue at the entrance (Phase 0) and routes it to Quick GPC or Deep GPC mode using four criteria: cause hypothesis, number of variables, risk and data. It is ZEVA\'s Layer 2.',
        'Mekanisme yang mengevaluasi setiap masalah perbaikan di pintu masuk (Phase 0) dan mengarahkannya ke mode Quick GPC atau Deep GPC dengan empat kriteria: dugaan penyebab, jumlah variabel, risiko, dan data. Ini Layer 2 ZEVA.')),
    g('quick-gpc', 'zeva', 'z2-04',
      T('Quick GPCモード', 'Quick GPC mode', 'Mode Quick GPC'),
      T('原因仮説があり、低リスクで、変数が少ない課題に適用する高速改善モードです（1日〜1週間）。「走りながら考える」アプローチでH-T-C-Aサイクルを回します。統計知識は不要です。',
        'The fast improvement mode (1 day – 1 week) for issues with a cause hypothesis, low risk and few variables. A "think while running" approach using the H-T-C-A cycle; no statistical knowledge required.',
        'Mode perbaikan cepat (1 hari – 1 minggu) untuk masalah dengan dugaan penyebab, risiko rendah, dan sedikit variabel. Pendekatan "berpikir sambil berlari" dengan siklus H-T-C-A; tidak memerlukan pengetahuan statistik.')),
    g('deep-gpc', 'zeva', 'z2-04',
      T('Deep GPCモード', 'Deep GPC mode', 'Mode Deep GPC'),
      T('原因不明、高リスク、または多変量の課題に適用する深耕解析モードです（1〜3ヶ月）。「止まって深く考える」アプローチでDMAICを用い、統計的に根本原因を特定します。',
        'The deep analysis mode (1–3 months) for issues with unknown cause, high risk or many variables. A "stop and think deeply" approach using DMAIC to identify root causes statistically.',
        'Mode analisis mendalam (1–3 bulan) untuk masalah dengan penyebab tidak diketahui, risiko tinggi, atau banyak variabel. Pendekatan "berhenti dan berpikir mendalam" dengan DMAIC untuk menemukan akar penyebab secara statistik.')),

    /* ---------- z2-05 ---------- */
    g('htca', 'zeva', 'z2-05',
      T('H-T-C-Aサイクル', 'H-T-C-A cycle', 'Siklus H-T-C-A'),
      T('Quick GPCの4ステップ改善サイクルで、Hypothesis（仮説設定）→ Trial（少量で試行）→ Check（即時確認）→ Action（標準化または再試行）です。',
        'The four-step improvement cycle of Quick GPC: Hypothesis → Trial (small quantity) → Check (immediate) → Action (standardize or retry).',
        'Siklus perbaikan empat langkah Quick GPC: Hypothesis → Trial (jumlah kecil) → Check (segera) → Action (standardisasi atau coba lagi).'),
      'H-T-C-A'),
    g('temporary-standard', 'zeva', 'z2-05',
      T('暫定標準', 'Temporary standard', 'Standar sementara'),
      T('Quick GPCで成功した条件を、正式な改訂を待たずに即日現場へ適用する仮の標準です。有効期限は最大30日で、その間に正式承認を得ます。適用は単一ライン限定で、変更前にいつでも戻せるようにします。',
        'A provisional standard that applies a successful Quick GPC condition on the same day without waiting for formal revision. Valid for up to 30 days, within which formal approval is obtained; limited to a single line and always reversible.',
        'Standar sementara yang menerapkan kondisi Quick GPC yang berhasil pada hari yang sama tanpa menunggu revisi resmi. Berlaku maksimal 30 hari dan dalam periode itu harus disetujui resmi; terbatas pada satu lini dan selalu dapat dikembalikan.')),
    g('knowledge-base', 'zeva', 'z2-05',
      T('ナレッジベース', 'Knowledge base', 'Basis pengetahuan'),
      T('Quick GPCのトライ結果（成功・失敗の両方）、Deep GPCの分析結果、変更したGPCバンドや標準作業を蓄積する共通データベースです。無駄な再実験を防ぎ、トリアージ精度を高めます。',
        'A shared database of Quick GPC trial results (both successes and failures), Deep GPC analyses, changed GPC bands and revised standard work. It prevents needless repeat experiments and improves triage accuracy.',
        'Basis data bersama yang menyimpan hasil uji Quick GPC (berhasil maupun gagal), analisis Deep GPC, GPC band yang diubah, dan kerja standar yang direvisi. Mencegah eksperimen berulang yang sia-sia dan meningkatkan akurasi triage.')),
    g('escalation', 'zeva', 'z2-05',
      T('エスカレーション', 'Escalation', 'Eskalasi'),
      T('Quick GPCからDeep GPCへ切り替えることです。目安は、H-T-C-Aを3回回しても効果がない、仮説が枯渇した、問題が再発する、影響範囲が想定より大きい、のいずれかです。',
        'Switching from Quick GPC to Deep GPC. Triggers: no effect after three H-T-C-A cycles, no hypotheses left, recurrence of the problem, or a larger impact than expected.',
        'Beralih dari Quick GPC ke Deep GPC. Pemicu: tidak ada efek setelah tiga siklus H-T-C-A, dugaan habis, masalah terulang, atau dampak lebih besar dari perkiraan.')),
    g('work-instruction', 'ie', 'z2-05',
      T('作業標準書（WI）', 'Work instruction', 'Instruksi kerja'),
      T('作業者が現場で使う、作業の手順・急所・品質基準を示した文書です。ZEVAでは「誰が読んでも一通りにしか解釈できない」レベルまで具体化し、写真や動画を活用します。',
        'A document used on the floor that shows work steps, key points and quality criteria. In ZEVA it is made so specific that it can be interpreted only one way by anyone, using photos and videos.',
        'Dokumen yang dipakai di lantai produksi berisi langkah kerja, poin penting, dan kriteria kualitas. Dalam ZEVA dibuat sangat spesifik sehingga hanya bisa ditafsirkan satu cara oleh siapa pun, dengan foto dan video.'),
      'WI'),

    /* ---------- z2-06 ---------- */
    g('pdca-s', 'zeva', 'z2-06',
      T('PDCA-S（PDCA+S）', 'PDCA-S (PDCA+S)', 'PDCA-S (PDCA+S)'),
      T('Plan・Do・Check・ActにStandardize（標準化）を加えたサイクルです。改善後の状態を維持・定着させる日常運用サイクルであり、ZEVAの原則③として改善を標準に還元し土台を更新し続けます。',
        'Plan, Do, Check, Act plus Standardize. It is the daily operation cycle that sustains the improved state, and as ZEVA principle ③ it feeds improvements back into standards and keeps updating the foundation.',
        'Plan, Do, Check, Act ditambah Standardize. Siklus operasi harian yang mempertahankan kondisi setelah perbaikan, dan sebagai prinsip ③ ZEVA mengembalikan perbaikan ke standar serta terus memperbarui fondasi.'),
      'PDCA-S'),
    g('sop', 'qc', 'z2-06',
      T('SOP（標準作業手順書）', 'SOP (Standard Operating Procedure)', 'SOP (Prosedur Operasi Standar)'),
      T('業務や工程の標準的な手順・条件・責任を定めた公式文書です。Deep GPC完了後はSOPを改訂し、教育とあわせて定着させます。',
        'An official document defining the standard steps, conditions and responsibilities of a job or process. After Deep GPC the SOP is revised and embedded together with training.',
        'Dokumen resmi yang menetapkan langkah, kondisi, dan tanggung jawab standar suatu pekerjaan atau proses. Setelah Deep GPC, SOP direvisi dan diterapkan bersama pelatihan.'),
      'SOP'),

    /* ---------- z3-01 ---------- */
    g('four-boxes', 'zeva', 'z3-01',
      T('4つの箱', 'Four boxes', 'Empat kotak'),
      T('理論値の論理的思考フレームワークで、①現状の値 ②現状のやり方 ③新たなやり方 ④目標の値 の4つを、結論と根拠を添えて埋めます。仮説と検証を往復しながら改善シナリオの精度を高めます。',
        'The logical thinking framework of theoretical-value improvement: ① current value, ② current way, ③ new way, ④ target value, each filled with a conclusion and grounds. Going back and forth between hypothesis and verification sharpens the improvement scenario.',
        'Kerangka berpikir logis nilai teoretis: ① nilai saat ini, ② cara saat ini, ③ cara baru, ④ nilai target, masing-masing diisi dengan kesimpulan dan dasar. Bolak-balik antara hipotesis dan verifikasi mempertajam skenario perbaikan.')),
    g('loss-structure', 'zeva', 'z3-01',
      T('ロス構造図', 'Loss structure chart', 'Diagram struktur kerugian'),
      T('現状の総時間を価値作業・準価値作業・無価値作業に分け、無価値作業を動作・停止・速度・品質・流れの5つのロスに分解して構成比を可視化した図です。品質ロス（不良・手直し・廃棄）の時間は、原因にかかわらず無価値作業に含めます。インパクトの大きいロスから着手する判断に使います。',
        'A chart that splits total actual time into value, semi-value and non-value work, breaks non-value work into five losses (motion, stop, speed, quality, flow) and shows their proportions. Quality-loss time (defects, repair, scrap) counts as non-value work whatever its cause. Used to decide which high-impact losses to tackle first.',
        'Diagram yang membagi total waktu aktual menjadi pekerjaan bernilai, semi-bernilai, dan tanpa nilai, memecah pekerjaan tanpa nilai menjadi lima kerugian (gerakan, henti, kecepatan, kualitas, aliran), dan menunjukkan proporsinya. Waktu kerugian kualitas (cacat, perbaikan, barang afkir) dihitung sebagai pekerjaan tanpa nilai apa pun penyebabnya. Digunakan untuk memutuskan kerugian berdampak besar mana yang ditangani lebih dulu.')),

    /* ---------- z3-02 ---------- */
    g('dmaic', 'qc', 'z3-02',
      T('DMAIC', 'DMAIC', 'DMAIC'),
      T('Define（定義）・Measure（測定）・Analyze（分析）・Improve（改善）・Control（管理）の5ステップ改善サイクルです。ZEVAではDeep GPCのサイクルとして、原因不明・高リスクな課題を統計的に解決します。',
        'The five-step improvement cycle Define, Measure, Analyze, Improve, Control. In ZEVA it is the Deep GPC cycle for statistically solving issues with unknown causes or high risk.',
        'Siklus perbaikan lima langkah Define, Measure, Analyze, Improve, Control. Dalam ZEVA merupakan siklus Deep GPC untuk menyelesaikan masalah dengan penyebab tak diketahui atau risiko tinggi secara statistik.'),
      'DMAIC'),
    g('msa', 'qc', 'z3-02',
      T('測定システム分析', 'Measurement System Analysis', 'Analisis Sistem Pengukuran'),
      T('測定器・測定者・方法を含む測定システムの誤差を評価する手法です。繰返し性・再現性（精度）と偏り・校正（正確さ）を確認し、データの信頼性を保証します。',
        'A method for evaluating the error of the measurement system (gauge, appraiser, method). It checks repeatability and reproducibility (precision) and bias/calibration (accuracy) to guarantee data reliability.',
        'Metode untuk mengevaluasi galat sistem pengukuran (alat, penilai, metode). Memeriksa repeatability dan reproducibility (presisi) serta bias/kalibrasi (akurasi) untuk menjamin keandalan data.'),
      'MSA'),
    g('doe', 'qc', 'z3-02',
      T('実験計画法', 'Design of Experiments', 'Desain Eksperimen'),
      T('複数の要因の条件を計画的に変えて実験し、少ない試行で要因の効果や交互作用、最適条件を求める手法です。DOEで意図的に振る変動は、排除すべきバラツキではなく学習の源泉です。',
        'A method that changes several factor conditions in a planned way to find factor effects, interactions and optimal conditions with few trials. Variation intentionally introduced in DOE is not variation to eliminate but a source of learning.',
        'Metode yang mengubah kondisi beberapa faktor secara terencana untuk menemukan efek faktor, interaksi, dan kondisi optimal dengan sedikit percobaan. Variasi yang sengaja dibuat dalam DOE bukan variasi yang harus dihilangkan, melainkan sumber pembelajaran.'),
      'DOE'),
    g('gage-rr', 'qc', 'z3-02',
      T('ゲージR&R', 'Gage R&R', 'Gage R&R'),
      T('測定の繰返し性（同じ人・同じ器具での誤差）と再現性（人による差）を定量化するMSAの代表手法です。目安として%GRR 10%未満は良好、10〜30%は条件付き、30%超は不可とされます。',
        'The typical MSA method quantifying repeatability (same appraiser and gauge) and reproducibility (between appraisers). Rule of thumb: %GRR < 10% good, 10–30% conditionally acceptable, > 30% unacceptable.',
        'Metode MSA yang umum untuk mengukur repeatability (penilai dan alat sama) dan reproducibility (antar penilai). Patokan: %GRR < 10% baik, 10–30% dapat diterima bersyarat, > 30% tidak dapat diterima.'),
      'GRR'),
    g('sipoc', 'qc', 'z3-02',
      T('SIPOC', 'SIPOC', 'SIPOC'),
      T('Supplier（供給者）・Input（入力）・Process（工程）・Output（出力）・Customer（顧客）の流れで工程の全体像を1枚に整理する図です。DMAICのDefineでスコープを決めるのに使います。',
        'A one-page overview of a process in the flow Supplier – Input – Process – Output – Customer. Used in the Define phase to set scope.',
        'Gambaran satu halaman proses dalam alur Supplier – Input – Process – Output – Customer. Digunakan pada fase Define untuk menetapkan cakupan.'),
      'SIPOC'),
    g('ctq', 'qc', 'z3-02',
      T('CTQ（品質重要特性）', 'CTQ (Critical to Quality)', 'CTQ (Critical to Quality)'),
      T('顧客要求を満たすために決定的に重要な、測定可能な製品・工程の特性です。DMAICのDefineで改善対象のYとして明確にします。',
        'A measurable product or process characteristic that is critical to meeting customer requirements. Clarified as the Y to improve in the Define phase.',
        'Karakteristik produk atau proses yang dapat diukur dan sangat penting untuk memenuhi kebutuhan pelanggan. Diperjelas sebagai Y yang akan diperbaiki pada fase Define.'),
      'CTQ'),
    g('regression', 'stat', 'z3-02',
      T('回帰分析', 'Regression analysis', 'Analisis regresi'),
      T('結果（Y）と1つまたは複数の要因（X）の関係を数式（回帰式）で表し、影響の大きさを推定する統計手法です。',
        'A statistical method that expresses the relationship between a result (Y) and one or more factors (X) as an equation and estimates the size of their effects.',
        'Metode statistik yang menyatakan hubungan antara hasil (Y) dan satu atau beberapa faktor (X) sebagai persamaan serta mengestimasi besarnya pengaruh.')),
    g('anova', 'stat', 'z3-02',
      T('分散分析', 'Analysis of variance', 'Analisis varians'),
      T('データ全体のバラツキを要因ごとの成分に分解し、群間（例：ロット間・作業者間）の平均の差が偶然か有意かを検定する統計手法です。',
        'A statistical method that decomposes total variation into components by factor and tests whether differences in means between groups (e.g. lots, operators) are significant or due to chance.',
        'Metode statistik yang menguraikan variasi total menjadi komponen per faktor dan menguji apakah perbedaan rata-rata antar grup (mis. lot, operator) signifikan atau kebetulan.'),
      'ANOVA'),
    g('hypothesis-test', 'stat', 'z3-02',
      T('仮説検定', 'Hypothesis testing', 'Uji hipotesis'),
      T('「差がない」という帰無仮説を立て、データからその仮説が棄却できるかを有意水準（例：5%）で判断する統計手法です。t検定やカイ二乗検定などがあります。',
        'A statistical procedure that sets a null hypothesis ("no difference") and decides from data whether it can be rejected at a significance level (e.g. 5%). Examples: t-test, chi-square test.',
        'Prosedur statistik yang menetapkan hipotesis nol ("tidak ada perbedaan") dan memutuskan dari data apakah dapat ditolak pada tingkat signifikansi (mis. 5%). Contoh: uji t, uji chi-kuadrat.')),
    g('control-plan', 'qc', 'z3-02',
      T('コントロールプラン', 'Control plan', 'Rencana kendali'),
      T('改善後の工程で、何を・どの頻度で・どの方法で測定し、異常時にどう対応するかを定めた管理計画書です。DMAICのControlで作成し、PDCA-Sに引き継ぎます。',
        'A document specifying what to measure, how often, by what method and how to react to abnormalities in the improved process. Created in the Control phase and handed over to PDCA-S.',
        'Dokumen yang menetapkan apa yang diukur, seberapa sering, dengan metode apa, dan bagaimana menanggapi abnormalitas pada proses yang telah diperbaiki. Dibuat pada fase Control dan diserahkan ke PDCA-S.')),
    g('pilot-run', 'qc', 'z3-02',
      T('パイロットラン', 'Pilot run', 'Uji coba (pilot run)'),
      T('本格展開の前に、限定した範囲・数量で改善策を試行し、効果と副作用を検証することです。DMAICのImproveで実施します。',
        'A trial of an improvement on a limited scope and quantity before full deployment, to verify effects and side effects. Performed in the Improve phase.',
        'Uji coba perbaikan pada cakupan dan jumlah terbatas sebelum penerapan penuh, untuk memverifikasi efek dan efek samping. Dilakukan pada fase Improve.')),

    /* ---------- z3-04 ---------- */
    g('dx', 'zeva', 'z3-04',
      T('DX（デジタルトランスフォーメーション）', 'DX (digital transformation)', 'DX (transformasi digital)'),
      T('経営やビジネスモデルの変革までを指す言葉です。ZEVAが扱うのは現場改善の加速で、その範囲を超えるため、この教材ではDXという語を使わず、デジタイゼーション（Level 2）とデジタライゼーション（Level 3）で説明します。',
        'A term that reaches as far as changing the business model. ZEVA is about accelerating shop-floor improvement, which is narrower, so this material avoids the word DX and speaks of digitisation (Level 2) and digitalisation (Level 3) instead.',
        'Istilah yang mencakup perubahan model bisnis. ZEVA berbicara tentang mempercepat perbaikan di lantai produksi, yang cakupannya lebih sempit, sehingga materi ini tidak memakai kata DX dan menggunakan digitisasi (Level 2) serta digitalisasi (Level 3).'),
      'DX'),
    g('dx-levels', 'zeva', 'z3-04',
      T('デジタル化の段階的実装モデル', 'Staged digitalisation model', 'Model implementasi digitalisasi bertahap'),
      T('デジタル化を必須条件ではなく加速装置と位置づけ、Level 1（アナログ）・Level 2（デジタイゼーション）・Level 3（デジタライゼーション）の3段階で実装するモデルです。どのレベルでもZEVAは機能し、デジタル化レベルは改善の質とは独立です。',
        'A model that treats digitalisation as an accelerator, not a prerequisite, implemented in three levels: Level 1 (analog), Level 2 (digitisation), Level 3 (digitalisation). ZEVA works at every level, and the digital level is independent of improvement quality.',
        'Model yang memosisikan digitalisasi sebagai akselerator, bukan prasyarat, diterapkan dalam tiga level: Level 1 (analog), Level 2 (digitisasi), Level 3 (digitalisasi). ZEVA berfungsi di setiap level, dan level digital tidak menentukan kualitas perbaikan.'))
  ]);
})();
